/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform routes accept Clerk `Authorization: Bearer` **or** the
  `ctx_platform_session` cookie (local/dev bridge). `POST /platform/auth/login`
  is disabled in production (HTTP 410) unless an explicit non-prod override
  is set.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
export interface ContactApiError {
  error: string;
  /** Present on public submit errors. */
  correlationId?: string;
}

export const CrmOkResponseValue = {
  ok: true,
} as const;
export type CrmOkResponse = typeof CrmOkResponseValue;

export interface CrmJsonMap {
  [key: string]: unknown;
}

export type CrmInquiryType =
  (typeof CrmInquiryType)[keyof typeof CrmInquiryType];

export const CrmInquiryType = {
  sales: "sales",
  general: "general",
  technical: "technical",
  billing: "billing",
  other: "other",
} as const;

export type CrmInquiryStatus =
  (typeof CrmInquiryStatus)[keyof typeof CrmInquiryStatus];

export const CrmInquiryStatus = {
  NEW: "NEW",
  TRIAGED: "TRIAGED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING_FOR_CUSTOMER: "WAITING_FOR_CUSTOMER",
  WAITING_INTERNAL: "WAITING_INTERNAL",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
  SPAM: "SPAM",
  DUPLICATE: "DUPLICATE",
  CANCELLED: "CANCELLED",
} as const;

export type CrmInquiryPriority =
  (typeof CrmInquiryPriority)[keyof typeof CrmInquiryPriority];

export const CrmInquiryPriority = {
  low: "low",
  normal: "normal",
  high: "high",
  urgent: "urgent",
} as const;

export type CrmQualificationStatus =
  (typeof CrmQualificationStatus)[keyof typeof CrmQualificationStatus];

export const CrmQualificationStatus = {
  UNASSESSED: "UNASSESSED",
  UNQUALIFIED: "UNQUALIFIED",
  MARKETING_QUALIFIED: "MARKETING_QUALIFIED",
  SALES_QUALIFIED: "SALES_QUALIFIED",
  HIGH_PRIORITY: "HIGH_PRIORITY",
  DISQUALIFIED: "DISQUALIFIED",
} as const;

export type CrmSlaInstanceStatus =
  (typeof CrmSlaInstanceStatus)[keyof typeof CrmSlaInstanceStatus];

export const CrmSlaInstanceStatus = {
  ON_TRACK: "ON_TRACK",
  AT_RISK: "AT_RISK",
  BREACHED: "BREACHED",
  COMPLETED: "COMPLETED",
} as const;

export type CrmMeetingBookingStatus =
  (typeof CrmMeetingBookingStatus)[keyof typeof CrmMeetingBookingStatus];

export const CrmMeetingBookingStatus = {
  INVITED: "INVITED",
  BOOKED: "BOOKED",
  CANCELLED: "CANCELLED",
  RESCHEDULED: "RESCHEDULED",
  NO_SHOW: "NO_SHOW",
  COMPLETED: "COMPLETED",
} as const;

export type CrmConfigStatus =
  (typeof CrmConfigStatus)[keyof typeof CrmConfigStatus];

export const CrmConfigStatus = {
  active: "active",
  disabled: "disabled",
} as const;

export type CrmStaffRole = (typeof CrmStaffRole)[keyof typeof CrmStaffRole];

export const CrmStaffRole = {
  owner: "owner",
  admin: "admin",
  sales: "sales",
  operator: "operator",
  analyst: "analyst",
} as const;

/**
 * Values from PLATFORM_PERMISSIONS in lib/crm/rbac.ts
 */
export type CrmPlatformPermission =
  (typeof CrmPlatformPermission)[keyof typeof CrmPlatformPermission];

export const CrmPlatformPermission = {
  inquiriesview: "inquiries.view",
  inquiriesreply: "inquiries.reply",
  inquiriesforward: "inquiries.forward",
  inquiriesnote: "inquiries.note",
  inquiriesassign: "inquiries.assign",
  inquiriesstatus: "inquiries.status",
  inquiriespriority: "inquiries.priority",
  inquiriestags: "inquiries.tags",
  inquiriesqualificationoverride: "inquiries.qualification.override",
  inquirieslead_scoreview: "inquiries.lead_score.view",
  inquiriesexport: "inquiries.export",
  inquiriesdelete: "inquiries.delete",
  templatesmanage: "templates.manage",
  workflowsmanage: "workflows.manage",
  routingmanage: "routing.manage",
  slamanage: "sla.manage",
  meetingsmanage: "meetings.manage",
  analyticsview: "analytics.view",
  configmanage: "config.manage",
} as const;

export interface ContactCountry {
  code: string;
  name: string;
  /** E.164 calling prefix including `+` */
  callingCode: string;
}

export interface CrmTaxonomyItem {
  id: string;
  kind: string;
  key: string;
  parentKey: string;
  label: string;
  /** @nullable */
  description?: string | null;
  sortOrder: number;
  active: boolean;
  metadata?: CrmJsonMap;
}

export type ContactBootstrapCountryDetectionSource =
  (typeof ContactBootstrapCountryDetectionSource)[keyof typeof ContactBootstrapCountryDetectionSource];

export const ContactBootstrapCountryDetectionSource = {
  ip: "ip",
  none: "none",
} as const;

export type ContactBootstrapBotProtectionFallback =
  (typeof ContactBootstrapBotProtectionFallback)[keyof typeof ContactBootstrapBotProtectionFallback];

export const ContactBootstrapBotProtectionFallback = {
  email: "email",
} as const;

export type ContactBootstrapBotProtection = {
  provider?: string;
  /** Public Turnstile site key. Never a secret. */
  siteKey?: string;
  scriptSrc?: string;
  action?: string;
  fallback?: ContactBootstrapBotProtectionFallback;
  proofRequired?: boolean;
};

export interface ContactBootstrap {
  countries: ContactCountry[];
  /** @nullable */
  detectedCountry: string | null;
  countryDetectionSource: ContactBootstrapCountryDetectionSource;
  termsVersion: string;
  privacyPolicyVersion: string;
  messageMaxLength: number;
  taxonomy: CrmTaxonomyItem[];
  botProtection?: ContactBootstrapBotProtection;
}

export interface ContactAnswerValue {
  /** @maxItems 20 */
  optionKeys?: string[];
  /** @maxLength 2000 */
  freeText?: string;
}

export type ContactSubmitRequestAnswers = { [key: string]: ContactAnswerValue };

export interface ContactSubmitRequest {
  /**
   * @minLength 1
   * @maxLength 80
   */
  firstName: string;
  /**
   * @minLength 1
   * @maxLength 80
   */
  lastName: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  jobTitle: string;
  /**
   * @minLength 1
   * @maxLength 160
   */
  companyName: string;
  /** @maxLength 254 */
  email: string;
  /**
   * ISO 3166-1 alpha-2
   * @minLength 2
   * @maxLength 2
   */
  country: string;
  /**
   * @minLength 4
   * @maxLength 32
   */
  phoneRaw: string;
  inquiryType: CrmInquiryType;
  /**
   * Required (min 1) when `inquiryType` is `sales`.
   * @maxItems 12
   */
  useCaseKeys?: string[];
  /** @maxLength 160 */
  useCaseOther?: string;
  /**
   * @minLength 10
   * @maxLength 8000
   */
  message: string;
  answers?: ContactSubmitRequestAnswers;
  termsAccepted: true;
  /** @maxLength 32 */
  locale?: string;
  attribution?: CrmJsonMap;
  /** Required. Replays return the original inquiry. */
  idempotencyKey: string;
  /**
   * Must be empty; any value yields HTTP 400.
   * @maxLength 200
   */
  honeypot?: string;
  /**
   * Provider proof token (Turnstile). Required when bootstrap.botProtection.proofRequired is true. Sent only over HTTPS in production.
   * @maxLength 2048
   */
  botProof?: string;
}

export interface ContactSubmitResponse {
  /**
   * Stable public reference `CTX-YYYY-NNNNNN`
   * @pattern ^CTX-[0-9]{4}-[0-9]{6}$
   */
  reference: string;
  qualified: boolean;
  /** @nullable */
  meetingUrl: string | null;
  firstName: string;
  correlationId: string;
}

export interface InboundEmailWebhookRequest {
  from: string;
  /** @maxLength 500 */
  subject?: string;
  /**
   * @minLength 1
   * @maxLength 20000
   */
  text: string;
  /** @maxLength 200 */
  messageId?: string;
  /** @maxLength 200 */
  inReplyTo?: string;
}

export interface SchedulingWebhookRequest {
  reference?: string;
  email?: string;
  scheduledAt?: string;
  externalBookingId?: string;
  status?: CrmMeetingBookingStatus;
}

export interface WebhookMatchResponse {
  matched: boolean;
  reference?: string;
}

export interface PlatformLoginRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 200
   */
  accessKey: string;
  /** @maxLength 120 */
  name?: string;
}

export interface PlatformStaffSession {
  id: string;
  email: string;
  name: string;
  role: CrmStaffRole;
  permissions: CrmPlatformPermission[];
}

export interface CrmStaff {
  id: string;
  /** @nullable */
  clerkUserId?: string | null;
  email: string;
  emailNormalized: string;
  name: string;
  role: string;
  permissions: string[];
  /** @nullable */
  teamId?: string | null;
  status: string;
  /** @nullable */
  lastLoginAt?: string | null;
  createdAt: string;
}

export interface CrmTeam {
  id: string;
  slug: string;
  name: string;
  /** @nullable */
  region?: string | null;
  roundRobinCursor: number;
  createdAt: string;
}

export interface CrmStaffAndTeams {
  staff: CrmStaff[];
  teams: CrmTeam[];
}

export interface CrmCompany {
  id: string;
  name: string;
  nameNormalized: string;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  website?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CrmContact {
  id: string;
  /** @nullable */
  companyId?: string | null;
  firstName: string;
  lastName: string;
  jobTitle: string;
  email: string;
  emailNormalized: string;
  country: string;
  /** @nullable */
  phoneRaw?: string | null;
  /** @nullable */
  phoneCountry?: string | null;
  /** @nullable */
  phoneCountryCallingCode?: string | null;
  /** @nullable */
  phoneNationalNumber?: string | null;
  /** @nullable */
  phoneE164?: string | null;
  /** @nullable */
  phoneValidationStatus?: string | null;
  /** @nullable */
  phoneType?: string | null;
  /** @nullable */
  locale?: string | null;
  lifecycleStage: string;
  createdAt: string;
  updatedAt: string;
}

export interface CrmInquiry {
  id: string;
  reference: string;
  contactId: string;
  /** @nullable */
  companyId?: string | null;
  status: CrmInquiryStatus;
  priority: CrmInquiryPriority;
  source: string;
  channel: string;
  inquiryType: CrmInquiryType;
  useCaseKeys: string[];
  /** @nullable */
  useCaseOther?: string | null;
  /** @nullable */
  assignedTeamId?: string | null;
  /** @nullable */
  assignedStaffId?: string | null;
  /** @nullable */
  assignedReason?: string | null;
  qualificationStatus: CrmQualificationStatus;
  qualificationScore: number;
  /** @nullable */
  qualificationGrade?: string | null;
  /** @nullable */
  qualificationModelId?: string | null;
  /** @nullable */
  qualificationModelVersion?: number | null;
  /** @nullable */
  systemQualificationStatus?: string | null;
  /** @nullable */
  humanOverrideStatus?: string | null;
  /** @nullable */
  humanOverrideReason?: string | null;
  /** @nullable */
  humanOverrideBy?: string | null;
  /** @nullable */
  humanOverrideAt?: string | null;
  /** @nullable */
  qualifiedAt?: string | null;
  lastActivityAt: string;
  /** @nullable */
  lastCustomerMessageAt?: string | null;
  /** @nullable */
  firstResponseAt?: string | null;
  /** @nullable */
  resolvedAt?: string | null;
  /** @nullable */
  closedAt?: string | null;
  /** @nullable */
  meetingOfferedAt?: string | null;
  spamScore: number;
  /** @nullable */
  idempotencyKey?: string | null;
  attribution?: CrmJsonMap;
  createdAt: string;
  updatedAt: string;
}

export interface CrmInquiryListItem {
  id: string;
  reference: string;
  createdAt: string;
  lastActivityAt: string;
  firstName: string;
  lastName: string;
  company: string;
  jobTitle: string;
  country: string;
  useCase: string[];
  qualificationStatus: CrmQualificationStatus;
  leadScore: number;
  /** @nullable */
  assignedTo: string | null;
  /** @nullable */
  assignedStaffId: string | null;
  status: CrmInquiryStatus;
  unread: boolean;
  /** @nullable */
  slaStatus: string | null;
  /** @nullable */
  slaDueAt: string | null;
  /** Always `false` in the current list handler. */
  hasMeeting: boolean;
}

export interface CrmInquiryListResponse {
  items: CrmInquiryListItem[];
  /** Count of rows matching SQL filters (before in-memory readState). */
  total: number;
  limit: number;
  /** Always 0 when keyset pagination is used (`sort=createdAt`). */
  offset: number;
  /** Opaque forward cursor. Null when this is the last page. */
  nextCursor?: string | null;
  cursor?: string | null;
}

export type CrmMessageVisibility =
  (typeof CrmMessageVisibility)[keyof typeof CrmMessageVisibility];

export const CrmMessageVisibility = {
  customer: "customer",
  internal: "internal",
} as const;

export interface CrmMessage {
  id: string;
  conversationId: string;
  inquiryId: string;
  kind: string;
  visibility: CrmMessageVisibility;
  channel: string;
  authorType: string;
  /** @nullable */
  authorStaffId?: string | null;
  /** @nullable */
  authorContactId?: string | null;
  /** @nullable */
  subject?: string | null;
  body: string;
  /** @nullable */
  bodyHtml?: string | null;
  /** @nullable */
  templateId?: string | null;
  /** @nullable */
  templateVersionId?: string | null;
  /** @nullable */
  externalMessageId?: string | null;
  /** @nullable */
  inReplyTo?: string | null;
  /** @nullable */
  forwardedTo?: string | null;
  mentions: string[];
  metadata?: CrmJsonMap;
  createdAt: string;
}

export interface CrmInquiryAnswer {
  id: string;
  inquiryId: string;
  questionKey: string;
  optionKeys: string[];
  /** @nullable */
  freeText?: string | null;
}

export interface CrmQualificationResult {
  id: string;
  inquiryId: string;
  /** @nullable */
  modelId?: string | null;
  modelVersion: number;
  score: number;
  /** @nullable */
  grade?: string | null;
  status: string;
  reasons: CrmJsonMap[];
  source: string;
  createdAt: string;
}

export interface CrmAuditEvent {
  id: string;
  actorType: string;
  /** @nullable */
  actorId?: string | null;
  action: string;
  entityType: string;
  entityId: string;
  /** @nullable */
  inquiryId?: string | null;
  /** @nullable */
  contactId?: string | null;
  beforeValue?: CrmJsonMap;
  afterValue?: CrmJsonMap;
  /** @nullable */
  workflowId?: string | null;
  /** @nullable */
  correlationId?: string | null;
  createdAt: string;
}

export interface CrmSlaInstance {
  id: string;
  inquiryId: string;
  policyId: string;
  policyVersion: number;
  measure: string;
  dueAt: string;
  status: CrmSlaInstanceStatus;
  /** @nullable */
  completedAt?: string | null;
  createdAt: string;
}

export interface CrmMeeting {
  id: string;
  /** @nullable */
  inquiryId?: string | null;
  /** @nullable */
  contactId?: string | null;
  /** @nullable */
  meetingTypeId?: string | null;
  /** @nullable */
  assignedStaffId?: string | null;
  /** @nullable */
  assignedTeamId?: string | null;
  bookingUrl: string;
  bookingStatus: CrmMeetingBookingStatus;
  /** @nullable */
  scheduledAt?: string | null;
  /** @nullable */
  cancelledAt?: string | null;
  /** @nullable */
  rescheduledAt?: string | null;
  /** @nullable */
  externalBookingId?: string | null;
  /** @nullable */
  timezone?: string | null;
  createdAt: string;
}

export interface CrmAiClassification {
  id: string;
  inquiryId: string;
  provider: string;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  confidence?: number | null;
  output: CrmJsonMap;
  createdAt: string;
}

export interface CrmWorkflowExecution {
  id: string;
  workflowId: string;
  workflowVersion: number;
  /** @nullable */
  inquiryId?: string | null;
  trigger: string;
  matched?: CrmJsonMap;
  status: string;
  /** @nullable */
  error?: string | null;
  idempotencyKey: string;
  createdAt: string;
}

export interface CrmTag {
  id: string;
  slug: string;
  label: string;
  /** @nullable */
  color?: string | null;
}

export interface CrmInquiryTagRef {
  id: string;
  slug: string;
  label: string;
}

export interface CrmInquiryDetail {
  inquiry: CrmInquiry;
  contact: CrmContact;
  company: CrmCompany | null;
  assignee: CrmStaff | null;
  messages: CrmMessage[];
  answers: CrmInquiryAnswer[];
  qualification: CrmQualificationResult[];
  audit: CrmAuditEvent[];
  sla: CrmSlaInstance[];
  meetings: CrmMeeting[];
  ai: CrmAiClassification[];
  executions: CrmWorkflowExecution[];
  tags: CrmInquiryTagRef[];
}

export interface CrmReadStateRequest {
  /** When true, clears the staff read cursor. */
  unread?: boolean;
}

export interface CrmBulkReadRequest {
  /**
   * @minItems 1
   * @maxItems 100
   */
  ids: string[];
  unread?: boolean;
}

export interface CrmReplyRequest {
  /**
   * @minLength 1
   * @maxLength 8000
   */
  body: string;
  templateKey?: string;
  /** Optimistic concurrency token from the inquiry updatedAt. */
  expectedUpdatedAt?: string;
}

export interface CrmNoteRequest {
  /**
   * @minLength 1
   * @maxLength 8000
   */
  body: string;
  expectedUpdatedAt?: string;
}

export interface CrmForwardRequest {
  to: string;
  /** @maxLength 2000 */
  note?: string;
  expectedUpdatedAt?: string;
}

export interface CrmAssignRequest {
  /** @nullable */
  staffId?: string | null;
  /** @nullable */
  teamId?: string | null;
}

export interface CrmStatusRequest {
  status: CrmInquiryStatus;
}

export interface CrmPriorityRequest {
  priority: CrmInquiryPriority;
}

export interface CrmTagSlugRequest {
  /**
   * @minLength 1
   * @maxLength 40
   */
  slug: string;
}

export interface CrmQualificationOverrideRequest {
  status: CrmQualificationStatus;
  /**
   * @minLength 3
   * @maxLength 500
   */
  reason: string;
}

export interface CrmMeetingInviteResponse {
  bookingUrl: string;
}

export interface CrmTemplate {
  id: string;
  key: string;
  internalName: string;
  /** @nullable */
  description?: string | null;
  category: string;
  channel: string;
  status: string;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  updatedBy?: string | null;
  /** @nullable */
  publishedAt?: string | null;
  /** @nullable */
  archivedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CrmTemplateVersion {
  id: string;
  templateId: string;
  versionNumber: number;
  language: string;
  subject: string;
  body: string;
  /** @nullable */
  changeSummary?: string | null;
  /** @nullable */
  changedBy?: string | null;
  createdAt: string;
}

export interface CrmTemplatesBundle {
  templates: CrmTemplate[];
  versions: CrmTemplateVersion[];
}

export interface CrmCreateTemplateRequest {
  /**
   * @minLength 2
   * @maxLength 80
   */
  key: string;
  /**
   * @minLength 2
   * @maxLength 120
   */
  internalName: string;
  /** @maxLength 40 */
  category: string;
  /** @maxLength 8 */
  language?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  subject: string;
  /**
   * @minLength 1
   * @maxLength 20000
   */
  body: string;
}

export interface CrmCreateTemplateVersionRequest {
  /** @maxLength 8 */
  language?: string;
  /** @minLength 1 */
  subject: string;
  /** @minLength 1 */
  body: string;
  /** @maxLength 200 */
  changeSummary?: string;
}

export interface CrmQualificationModel {
  id: string;
  key: string;
  name: string;
  version: number;
  status: string;
  thresholds: CrmJsonMap;
  rules: CrmJsonMap[];
  /** @nullable */
  publishedAt?: string | null;
  createdAt: string;
}

export interface CrmWorkflow {
  id: string;
  key: string;
  name: string;
  status: string;
  version: number;
  trigger: string;
  conditions: CrmJsonMap[];
  actions: CrmJsonMap[];
  createdAt: string;
  updatedAt: string;
}

export interface CrmRoutingRule {
  id: string;
  name: string;
  priority: number;
  status: string;
  conditions: CrmJsonMap[];
  strategy: string;
  /** @nullable */
  teamId?: string | null;
  /** @nullable */
  staffId?: string | null;
  /** @nullable */
  reasonTemplate?: string | null;
  createdAt: string;
}

export interface CrmSlaPolicy {
  id: string;
  key: string;
  name: string;
  version: number;
  status: string;
  firstResponseMinutes: number;
  /** @nullable */
  nextResponseMinutes?: number | null;
  /** @nullable */
  resolutionMinutes?: number | null;
  conditions: CrmJsonMap[];
  createdAt: string;
}

export interface CrmMeetingType {
  id: string;
  key: string;
  name: string;
  durationMinutes: number;
  timezone: string;
  bookingUrl: string;
  /** @nullable */
  teamId?: string | null;
  calendarSource: string;
  status: string;
}

export interface CrmMacro {
  id: string;
  key: string;
  name: string;
  /** @nullable */
  description?: string | null;
  actions: CrmJsonMap[];
  status: string;
  createdAt: string;
}

export interface CrmConfigBundle {
  taxonomy: CrmTaxonomyItem[];
  models: CrmQualificationModel[];
  workflows: CrmWorkflow[];
  routing: CrmRoutingRule[];
  sla: CrmSlaPolicy[];
  meetings: CrmMeetingType[];
  macros: CrmMacro[];
  tags: CrmTag[];
}

export interface CrmUpdateTaxonomyRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  label?: string;
  sortOrder?: number;
  active?: boolean;
}

export type CrmUpdateQualificationModelRequestThresholds = {
  [key: string]: number;
};

export interface CrmUpdateQualificationModelRequest {
  thresholds: CrmUpdateQualificationModelRequestThresholds;
  rules: CrmJsonMap[];
  name?: string;
}

export interface CrmUpdateWorkflowRequest {
  name?: string;
  status?: CrmConfigStatus;
  conditions?: CrmJsonMap[];
  actions?: CrmJsonMap[];
}

export interface CrmUpdateRoutingRequest {
  name?: string;
  priority?: number;
  status?: CrmConfigStatus;
  conditions?: CrmJsonMap[];
  strategy?: string;
  /** @nullable */
  teamId?: string | null;
  /** @nullable */
  staffId?: string | null;
  reasonTemplate?: string;
}

export interface CrmUpdateSlaRequest {
  name?: string;
  firstResponseMinutes?: number;
  /** @nullable */
  nextResponseMinutes?: number | null;
  /** @nullable */
  resolutionMinutes?: number | null;
  conditions?: CrmJsonMap[];
  status?: CrmConfigStatus;
}

export interface CrmUpdateMeetingTypeRequest {
  name?: string;
  bookingUrl?: string;
  durationMinutes?: number;
  timezone?: string;
  status?: CrmConfigStatus;
}

export interface CrmNotification {
  id: string;
  staffId: string;
  /** @nullable */
  inquiryId?: string | null;
  type: string;
  title: string;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  readAt?: string | null;
  createdAt: string;
}

export interface CrmSavedView {
  id: string;
  staffId: string;
  name: string;
  filters: CrmJsonMap;
  /** @nullable */
  columns?: string[] | null;
  sort?: CrmJsonMap;
  createdAt: string;
}

export interface CrmCreateSavedViewRequest {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name: string;
  filters: CrmJsonMap;
}

export interface CrmUpdateSavedViewRequest {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name?: string;
  filters?: CrmJsonMap;
  columns?: string[];
  sort?: CrmJsonMap;
}

export interface CrmAnalyticsTotals {
  total: number;
  qualified: number;
  open: number;
}

export interface CrmAnalyticsCountryRow {
  country: string;
  count: number;
}

export interface CrmAnalyticsEventRow {
  event: string;
  count: number;
}

export interface CrmAnalyticsSlaCounts {
  breached: number;
  onTrack: number;
  atRisk: number;
}

export interface CrmAnalyticsResponse {
  totals: CrmAnalyticsTotals;
  byCountry: CrmAnalyticsCountryRow[];
  events: CrmAnalyticsEventRow[];
  sla: CrmAnalyticsSlaCounts;
}

export interface CrmAuditListResponse {
  items: CrmAuditEvent[];
  total: number;
  limit: number;
  offset: number;
}

export interface CrmConsentRecord {
  id: string;
  contactId: string;
  /** @nullable */
  inquiryId?: string | null;
  kind: string;
  granted: boolean;
  /** @nullable */
  termsVersion?: string | null;
  /** @nullable */
  privacyPolicyVersion?: string | null;
  /** @nullable */
  ip?: string | null;
  /** @nullable */
  userAgent?: string | null;
  createdAt: string;
}

export type CrmDsarExportStatus =
  (typeof CrmDsarExportStatus)[keyof typeof CrmDsarExportStatus];

export const CrmDsarExportStatus = {
  pending: "pending",
  running: "running",
  ready: "ready",
  failed: "failed",
  cancelled: "cancelled",
} as const;

export interface CrmDsarExportAccepted {
  exportId: string;
  status: CrmDsarExportStatus;
  contactId: string;
}

export interface CrmDsarExport {
  exportId: string;
  status: CrmDsarExportStatus;
  contactId: string;
  createdAt: string;
  /** @nullable */
  completedAt?: string | null;
  /** @nullable */
  expiresAt?: string | null;
  /** @nullable */
  downloadUrl?: string | null;
  /** @nullable */
  error?: string | null;
}

export type CrmDeadLetterJobsResponseItemsItem = { [key: string]: unknown };

export interface CrmDeadLetterJobsResponse {
  items: CrmDeadLetterJobsResponseItemsItem[];
}

export type CrmJobEffectsListResponseEffectsItem = { [key: string]: unknown };

export type CrmJobEffectsListResponseMetrics = { [key: string]: unknown };

export interface CrmJobEffectsListResponse {
  effects: CrmJobEffectsListResponseEffectsItem[];
  metrics?: CrmJobEffectsListResponseMetrics;
}

export type CrmConfigChangeListResponseItemsItem = { [key: string]: unknown };

export interface CrmConfigChangeListResponse {
  items: CrmConfigChangeListResponseItemsItem[];
}

export type CrmConfigChangeCreateRequestAfterValue = { [key: string]: unknown };

export type CrmConfigChangeCreateRequestBeforeValue = {
  [key: string]: unknown;
} | null;

export interface CrmConfigChangeCreateRequest {
  /**
   * @minLength 2
   * @maxLength 80
   */
  entityType: string;
  /**
   * @minLength 1
   * @maxLength 80
   */
  entityId: string;
  afterValue: CrmConfigChangeCreateRequestAfterValue;
  beforeValue?: CrmConfigChangeCreateRequestBeforeValue;
  effectiveAt?: string;
  /** @maxLength 500 */
  rationale?: string;
}

export type CrmBulkMutationResultFailedItem = {
  id?: string;
  reason?: string;
};

export interface CrmBulkMutationResult {
  updated?: number;
  succeeded?: string[];
  failed?: CrmBulkMutationResultFailedItem[];
}

export type CrmMacroUpdateStatus =
  (typeof CrmMacroUpdateStatus)[keyof typeof CrmMacroUpdateStatus];

export const CrmMacroUpdateStatus = {
  active: "active",
  disabled: "disabled",
} as const;

export type CrmMacroUpdateActionsItem = { [key: string]: unknown };

export interface CrmMacroUpdate {
  name?: string;
  description?: string | null;
  status?: CrmMacroUpdateStatus;
  actions?: CrmMacroUpdateActionsItem[];
  /** @maxLength 500 */
  rationale?: string;
}

export interface CrmTagUpdate {
  label?: string;
  color?: string | null;
  /** @maxLength 500 */
  rationale?: string;
}

export interface CrmNotificationPolicyUpdate {
  channels?: string[];
  slaBreach?: boolean;
  assignment?: boolean;
  /** @maxLength 500 */
  rationale?: string;
}

export interface MarketingDocument {
  id: string;
  slug: string;
  contentType: string;
  updatedAt: string;
}

export interface MarketingDocumentList {
  documents: MarketingDocument[];
}

export type MarketingVersionStatus =
  (typeof MarketingVersionStatus)[keyof typeof MarketingVersionStatus];

export const MarketingVersionStatus = {
  draft: "draft",
  in_review: "in_review",
  changes_requested: "changes_requested",
  approved: "approved",
  scheduled: "scheduled",
  published: "published",
  superseded: "superseded",
  archived: "archived",
} as const;

export type MarketingVersionBody = { [key: string]: unknown };

export interface MarketingVersion {
  id: string;
  documentId: string;
  locale: string;
  version: number;
  status: MarketingVersionStatus;
  title: string;
  /** @nullable */
  summary?: string | null;
  body: MarketingVersionBody;
  /** @nullable */
  seoTitle?: string | null;
  /** @nullable */
  seoDescription?: string | null;
  lockVersion: number;
  [key: string]: unknown;
}

export interface MarketingVersionEnvelope {
  version: MarketingVersion;
}

export interface MarketingDocumentVersionPair {
  document: MarketingDocument;
  version: MarketingVersion;
}

export interface MarketingDocumentVersions {
  document: MarketingDocument;
  versions: MarketingVersion[];
}

export type MarketingDraftCreateBody = { [key: string]: unknown };

export interface MarketingDraftCreate {
  /** @minLength 1 */
  slug: string;
  locale?: string;
  /** @minLength 1 */
  title: string;
  summary?: string;
  body?: MarketingDraftCreateBody;
  seoTitle?: string;
  seoDescription?: string;
  robots?: string;
}

export type MarketingDraftPatchBody = { [key: string]: unknown };

export interface MarketingDraftPatch {
  /** @minimum 1 */
  expectedLockVersion: number;
  /** @minLength 1 */
  title?: string;
  /** @nullable */
  summary?: string | null;
  body?: MarketingDraftPatchBody;
  /** @nullable */
  seoTitle?: string | null;
  /** @nullable */
  seoDescription?: string | null;
  /** @nullable */
  robots?: string | null;
}

export type MarketingTransitionBodyTransition =
  (typeof MarketingTransitionBodyTransition)[keyof typeof MarketingTransitionBodyTransition];

export const MarketingTransitionBodyTransition = {
  submit_review: "submit_review",
  request_changes: "request_changes",
  approve: "approve",
  reject: "reject",
  schedule: "schedule",
  publish: "publish",
  unpublish: "unpublish",
  archive: "archive",
  revise: "revise",
} as const;

export interface MarketingTransitionBody {
  transition: MarketingTransitionBodyTransition;
  /** @minimum 1 */
  expectedLockVersion?: number;
  scheduledAt?: string;
  /** @minLength 3 */
  reason?: string;
}

export type MarketingPreviewEnvelopePreview = { [key: string]: unknown };

export interface MarketingPreviewEnvelope {
  preview: MarketingPreviewEnvelopePreview;
}

export type MarketingVersionCompareLeft = { [key: string]: unknown };

export type MarketingVersionCompareRight = { [key: string]: unknown };

export type MarketingVersionCompareDiffsItem = {
  field: string;
  before?: unknown;
  after?: unknown;
};

export interface MarketingVersionCompare {
  left: MarketingVersionCompareLeft;
  right: MarketingVersionCompareRight;
  diffs: MarketingVersionCompareDiffsItem[];
}

export interface MarketingAuditRow {
  id: string;
  action: string;
  createdAt: string;
  [key: string]: unknown;
}

export interface MarketingDocumentAudit {
  document: MarketingDocument;
  audit: MarketingAuditRow[];
}

export type CrmLockEntityType =
  (typeof CrmLockEntityType)[keyof typeof CrmLockEntityType];

export const CrmLockEntityType = {
  inquiry: "inquiry",
  marketing_version: "marketing_version",
  config_change: "config_change",
} as const;

export interface CrmLockEntityRequest {
  entityType: CrmLockEntityType;
  entityId: string;
  /** @maxLength 40 */
  intent?: string;
}

export interface CrmRecordLock {
  id: string;
  entityType: CrmLockEntityType;
  entityId: string;
  holderStaffId?: string;
  [key: string]: unknown;
}

export interface CrmPresenceSnapshot {
  [key: string]: unknown;
}

export type CrmExportCreateRequestFilters = { [key: string]: unknown };

export interface CrmExportCreateRequest {
  filters?: CrmExportCreateRequestFilters;
  /** @maxItems 40 */
  columns?: string[];
}

export interface CrmExportJob {
  id: string;
  status?: string;
  [key: string]: unknown;
}

export type CrmAttachmentListResponseAttachmentsItem = {
  [key: string]: unknown;
};

export interface CrmAttachmentListResponse {
  attachments: CrmAttachmentListResponseAttachmentsItem[];
}

export interface CrmDsarCorrectionPatch {
  /** @maxLength 120 */
  firstName?: string;
  /** @maxLength 120 */
  lastName?: string;
  /** @maxLength 200 */
  jobTitle?: string;
  /** @maxLength 320 */
  email?: string;
  /** @maxLength 40 */
  phone?: string;
}

export interface CrmGovernedDraftCreated {
  changeId: string;
  status: string;
  message: string;
}

export interface CrmBusinessCalendarUpdate {
  /** @maxLength 80 */
  timeZone: string;
  /** @minItems 1 */
  weekdays: number[];
  /**
   * @minimum 0
   * @maximum 23
   */
  openHour?: number;
  /**
   * @minimum 1
   * @maximum 24
   */
  closeHour?: number;
  holidays?: string[];
  /** @maxLength 500 */
  rationale?: string;
}

export interface CrmRetentionPolicyUpdate {
  /**
   * @minimum 1
   * @maximum 3650
   */
  retainDays: number;
  anonymizeMessages?: boolean;
  /** @maxLength 500 */
  rationale?: string;
}

export interface CrmSpamBotPolicyUpdate {
  /**
   * @minimum 0
   * @maximum 100
   */
  blockScore: number;
  honeypotReject?: boolean;
  /** @maxLength 500 */
  rationale?: string;
}

export type CrmContactDuplicatesResponseItemsItem = {
  id?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phoneE164?: string | null;
  companyId?: string | null;
  updatedAt?: string;
  [key: string]: unknown;
};

export type CrmContactDuplicatesResponseMatchOn = {
  email?: string | null;
  phone?: string | null;
};

export interface CrmContactDuplicatesResponse {
  items: CrmContactDuplicatesResponseItemsItem[];
  matchOn: CrmContactDuplicatesResponseMatchOn;
}

/**
 * Missing or invalid staff session
 */
export type UnauthorizedResponse = ContactApiError;

/**
 * Authenticated but missing `x-permission`
 */
export type ForbiddenResponse = ContactApiError;

/**
 * Request origin is not on the CORS allowlist
 */
export type ForbiddenOriginResponse = ContactApiError;

/**
 * Entity not found
 */
export type NotFoundResponse = ContactApiError;

/**
 * Invalid request body or query
 */
export type BadRequestResponse = ContactApiError;

/**
 * Optimistic concurrency conflict or invalid state transition
 */
export type ConflictResponse = ContactApiError;

/**
 * Planned endpoint; handler is not wired
 */
export type NotImplementedResponse = ContactApiError;

/**
 * Admin or public rate limit exceeded
 */
export type RateLimitedResponse = ContactApiError;

/**
 * Inbox default 50, capped at 100.
 */
export type PageLimitParameter = number;

/**
 * Deprecated for `sort=createdAt` (keyset). Still accepted for score/lastActivityAt first-page offset only until those sorts gain cursors.
 */
export type PageOffsetParameter = number;

/**
 * Opaque keyset cursor (createdAt + id). Forward page token from `nextCursor`.
 */
export type PageCursorParameter = string;

/**
 * Correlation id echoed on public submit responses. Generated if omitted.
 */
export type XRequestIdParameter = string;

/**
 * Recommended client header for retry-safe writes. Public submit currently
requires the same UUID in the JSON body field `idempotencyKey`; the
server does not read this header yet. Planned DSAR export should honor it.

 */
export type IdempotencyKeyHeaderParameter = string;

/**
 * Required when the corresponding `CONTACT_*_WEBHOOK_SECRET` env is set.
 */
export type WebhookSecretParameter = string;

/**
 * Cloudflare country code. `XX` and `T1` are ignored.
 */
export type CfIpCountryParameter = string;

export type MicrosoftGraphMailWebhookParams = {
  /**
   * Graph subscription validation handshake token
   */
  validationToken?: string;
};

export type MicrosoftGraphMailWebhookBodyValueItem = { [key: string]: unknown };

export type MicrosoftGraphMailWebhookBody = {
  value?: MicrosoftGraphMailWebhookBodyValueItem[];
  [key: string]: unknown;
};

export type MicrosoftGraphMailWebhook202 = { [key: string]: unknown };

export type WhatsappContactWebhookGetParams = {
  "hub.mode"?: string;
  "hub.verify_token"?: string;
  "hub.challenge"?: string;
};

export type WhatsappContactWebhookBody = { [key: string]: unknown };

export type MetaContactWebhookGetParams = {
  "hub.mode"?: string;
  "hub.verify_token"?: string;
  "hub.challenge"?: string;
};

export type MetaContactWebhookBody = { [key: string]: unknown };

export type XContactWebhookGetParams = {
  crc_token?: string;
};

export type XContactWebhookGet200 = { [key: string]: unknown };

export type XContactWebhookBody = { [key: string]: unknown };

export type ListPlatformContactChannels200 = { [key: string]: unknown };

export type RefreshPlatformContactChannelsHealth200 = {
  [key: string]: unknown;
};

export type ListPlatformContactIdentitiesParams = {
  contactId: string;
};

export type ListPlatformContactIdentities200 = { [key: string]: unknown };

export type LinkPlatformContactIdentityBody = {
  contactId: string;
};

export type RetryPlatformContactMessage200 = { [key: string]: unknown };

export type ListPlatformContactInquiriesParams = {
  /**
   * Inbox default 50, capped at 100.
   * @minimum 1
   * @maximum 100
   */
  limit?: PageLimitParameter;
  /**
   * Deprecated for `sort=createdAt` (keyset). Still accepted for score/lastActivityAt first-page offset only until those sorts gain cursors.
   * @minimum 0
   */
  offset?: PageOffsetParameter;
  /**
   * Opaque keyset cursor (createdAt + id). Forward page token from `nextCursor`.
   */
  cursor?: PageCursorParameter;
  /**
   * `score` sorts by `qualificationScore`.
   */
  sort?: ListPlatformContactInquiriesSort;
  dir?: ListPlatformContactInquiriesDir;
  status?: CrmInquiryStatus;
  qualificationStatus?: CrmQualificationStatus;
  /**
   * ISO 3166-1 alpha-2; compared uppercased.
   * @minLength 2
   * @maxLength 2
   */
  country?: string;
  assignedStaffId?: string;
  source?: string;
  /**
   * Inclusive lower bound on `createdAt` (`new Date(from)`).
   */
  from?: string;
  /**
   * Inclusive upper bound on `createdAt` (`new Date(to)`).
   */
  to?: string;
  /**
   * Case-insensitive substring on name, email, phone, company, or reference.
   */
  search?: string;
  readState?: ListPlatformContactInquiriesReadState;
  /**
   * Filter by inquiry type (e.g. sales, support).
   */
  inquiryType?: string;
  /**
   * Filter by origin channel (website, whatsapp, instagram, facebook, tiktok, x, linkedin, microsoft365).
   */
  channel?: string;
  priority?: string;
};

export type ListPlatformContactInquiriesSort =
  (typeof ListPlatformContactInquiriesSort)[keyof typeof ListPlatformContactInquiriesSort];

export const ListPlatformContactInquiriesSort = {
  createdAt: "createdAt",
  lastActivityAt: "lastActivityAt",
  score: "score",
} as const;

export type ListPlatformContactInquiriesDir =
  (typeof ListPlatformContactInquiriesDir)[keyof typeof ListPlatformContactInquiriesDir];

export const ListPlatformContactInquiriesDir = {
  asc: "asc",
  desc: "desc",
} as const;

export type ListPlatformContactInquiriesReadState =
  (typeof ListPlatformContactInquiriesReadState)[keyof typeof ListPlatformContactInquiriesReadState];

export const ListPlatformContactInquiriesReadState = {
  unread: "unread",
  read: "read",
} as const;

export type ConvertPlatformInquiryLeadBody = {
  opportunityName?: string;
  note?: string;
};

export type MergePlatformContactsBody = {
  winnerId: string;
  loserId: string;
};

export type ListPlatformContactDuplicatesParams = {
  email?: string;
  phone?: string;
};

export type ListPlatformDeadLetterJobsParams = {
  q?: string;
  type?: string;
};

export type ReplayPlatformDeadLetterJobBody = {
  /** @minLength 5 */
  reason: string;
};

export type ReplayPlatformDeadLetterJob200 = {
  replayed: boolean;
  id: string;
};

export type ListPlatformJobEffectsParams = {
  status?: string;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};

export type GetPlatformJobEffect200Effect = { [key: string]: unknown };

export type GetPlatformJobEffect200 = {
  effect: GetPlatformJobEffect200Effect;
};

export type ReconcilePlatformJobEffect200 = {
  key: string;
  outcome: string;
};

export type ReplayPlatformJobEffectBody = {
  reason: string;
};

export type CreatePlatformDsarRequestBodyRequestType =
  (typeof CreatePlatformDsarRequestBodyRequestType)[keyof typeof CreatePlatformDsarRequestBodyRequestType];

export const CreatePlatformDsarRequestBodyRequestType = {
  access: "access",
  export: "export",
  correction: "correction",
  deletion: "deletion",
  objection: "objection",
} as const;

export type CreatePlatformDsarRequestBody = {
  contactId: string;
  requestType: CreatePlatformDsarRequestBodyRequestType;
  notes?: string;
};

export type TransitionPlatformDsarRequestBody = {
  status: string;
  identityVerified?: boolean;
  legalExceptionReason?: string;
  rejectionReason?: string;
};

export type CorrectPlatformDsarRequest200 = { [key: string]: unknown };

export type DeletePlatformDsarRequest200 = { [key: string]: unknown };

export type ObjectPlatformDsarRequestBody = {
  notes?: string;
};

export type ObjectPlatformDsarRequest200 = { [key: string]: unknown };

export type ListPlatformAttachmentsParams = {
  /**
   * Filter by malwareStatus (e.g. quarantined, clean, pending)
   */
  status?: string;
};

export type CreatePlatformAttachmentBodyVisibility =
  (typeof CreatePlatformAttachmentBodyVisibility)[keyof typeof CreatePlatformAttachmentBodyVisibility];

export const CreatePlatformAttachmentBodyVisibility = {
  internal: "internal",
  customer: "customer",
} as const;

export type CreatePlatformAttachmentBody = {
  filename: string;
  mimeType: string;
  contentBase64: string;
  inquiryId?: string;
  contactId?: string;
  visibility?: CreatePlatformAttachmentBodyVisibility;
};

export type ReleasePlatformAttachmentQuarantineBody = {
  reason?: string;
};

export type ReleasePlatformAttachmentQuarantine200Attachment = {
  [key: string]: unknown;
};

export type ReleasePlatformAttachmentQuarantine200 = {
  attachment: ReleasePlatformAttachmentQuarantine200Attachment;
};

export type ConvertPlatformInquiryOpportunityBody = {
  idempotencyKey: string;
  amountCents?: number;
  currency?: string;
};

export type GetPlatformContactAnalyticsParams = {
  from?: string;
  to?: string;
  timeZone?: string;
  format?: GetPlatformContactAnalyticsFormat;
};

export type GetPlatformContactAnalyticsFormat =
  (typeof GetPlatformContactAnalyticsFormat)[keyof typeof GetPlatformContactAnalyticsFormat];

export const GetPlatformContactAnalyticsFormat = {
  json: "json",
  csv: "csv",
} as const;

export type BulkAssignPlatformInquiriesBody = {
  ids: string[];
  staffId: string;
  confirm: true;
};

export type BulkStatusPlatformInquiriesBody = {
  ids: string[];
  status: string;
  confirm: true;
};

export type ListPlatformConfigChangesParams = {
  entityType?: string;
};

export type CreatePlatformConfigChange201 = { [key: string]: unknown };

export type ActPlatformConfigChangeBody = {
  expectedLockVersion: number;
  expectedPublishedVersion?: number;
  /** @maxLength 500 */
  rationale?: string;
  emergencyBypass?: boolean;
  /** @maxLength 500 */
  emergencyReason?: string;
};

export type ActPlatformConfigChange409 = {
  error?: string;
  code?: string;
  currentLockVersion?: number | null;
  currentStatus?: string | null;
  currentPublishedVersion?: number | null;
};

export type PostPlatformGovernanceDsarExportBody = {
  contactId: string;
};

export type PostPlatformLegalHoldBody = {
  contactId?: string;
  inquiryId?: string;
  reason: string;
};

export type ReleasePlatformLegalHold200 = { [key: string]: unknown };

export type RunPlatformRetention200 = {
  processed: number;
};

export type InvitePlatformStaffBodyRole =
  (typeof InvitePlatformStaffBodyRole)[keyof typeof InvitePlatformStaffBodyRole];

export const InvitePlatformStaffBodyRole = {
  owner: "owner",
  admin: "admin",
  sales: "sales",
  operator: "operator",
  analyst: "analyst",
} as const;

export type InvitePlatformStaffBody = {
  email: string;
  role?: InvitePlatformStaffBodyRole;
};

export type ListPlatformContactAuditParams = {
  /**
   * Inbox default 50, capped at 100.
   * @minimum 1
   * @maximum 100
   */
  limit?: PageLimitParameter;
  inquiryId?: string;
};

export type GetPlatformContactPresenceParams = {
  entityType: CrmLockEntityType;
  entityId: string;
};

export type HeartbeatPlatformContactPresence200Presence = {
  [key: string]: unknown;
};

export type HeartbeatPlatformContactPresence200 = {
  presence: HeartbeatPlatformContactPresence200Presence;
};

export type AcquirePlatformRecordLock201 = {
  lock: CrmRecordLock;
};

export type HeartbeatPlatformRecordLock200 = {
  lock: CrmRecordLock;
};

export type ReleasePlatformRecordLock200 = { [key: string]: unknown };

export type OverridePlatformRecordLockBody = {
  /**
   * @minLength 5
   * @maxLength 500
   */
  reason: string;
};

export type OverridePlatformRecordLock200 = {
  lock: CrmRecordLock;
};

export type CreatePlatformContactExport202 = {
  job: CrmExportJob;
};

export type ListPlatformContactExportsParams = {
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};

export type ListPlatformContactExports200 = {
  jobs: CrmExportJob[];
};

export type GetPlatformContactExport200 = {
  job: CrmExportJob;
};

export type CancelPlatformContactExport200 = {
  job: CrmExportJob;
};

export type ListPlatformMarketingPublishFailures200FailuresItem = {
  [key: string]: unknown;
};

export type ListPlatformMarketingPublishFailures200 = {
  failures: ListPlatformMarketingPublishFailures200FailuresItem[];
};

export type ReconcilePlatformMarketingPublishBodyKind =
  (typeof ReconcilePlatformMarketingPublishBodyKind)[keyof typeof ReconcilePlatformMarketingPublishBodyKind];

export const ReconcilePlatformMarketingPublishBodyKind = {
  cache: "cache",
  notify: "notify",
  all: "all",
} as const;

export type ReconcilePlatformMarketingPublishBody = {
  kind?: ReconcilePlatformMarketingPublishBodyKind;
};

export type ReconcilePlatformMarketingPublish200Result = {
  [key: string]: unknown;
};

export type ReconcilePlatformMarketingPublish200 = {
  result: ReconcilePlatformMarketingPublish200Result;
};
