/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform routes accept Clerk `Authorization: Bearer` **or** the
  `ctx_platform_session` cookie (local/dev bridge). `POST /platform/auth/login`
  is disabled in production (HTTP 410) unless an explicit non-prod override
  is set.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
import type { ContactSubmitRequestAnswers } from "./contactSubmitRequestAnswers";
import type { CrmInquiryType } from "./crmInquiryType";
import type { CrmJsonMap } from "./crmJsonMap";

export interface ContactSubmitRequest {
  /**
   * @minLength 1
   * @maxLength 80
   */
  firstName: string;
  /**
   * @minLength 1
   * @maxLength 80
   */
  lastName: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  jobTitle: string;
  /**
   * @minLength 1
   * @maxLength 160
   */
  companyName: string;
  /** @maxLength 254 */
  email: string;
  /**
   * ISO 3166-1 alpha-2
   * @minLength 2
   * @maxLength 2
   */
  country: string;
  /**
   * @minLength 4
   * @maxLength 32
   */
  phoneRaw: string;
  inquiryType: CrmInquiryType;
  /**
   * Required (min 1) when `inquiryType` is `sales`.
   * @maxItems 12
   */
  useCaseKeys?: string[];
  /** @maxLength 160 */
  useCaseOther?: string;
  /**
   * @minLength 10
   * @maxLength 8000
   */
  message: string;
  answers?: ContactSubmitRequestAnswers;
  termsAccepted: true;
  /** @maxLength 32 */
  locale?: string;
  attribution?: CrmJsonMap;
  /** Required. Replays return the original inquiry. */
  idempotencyKey: string;
  /**
   * Must be empty; any value yields HTTP 400.
   * @maxLength 200
   */
  honeypot?: string;
  /**
   * Provider proof token (Turnstile). Required when bootstrap.botProtection.proofRequired is true. Sent only over HTTPS in production.
   * @maxLength 2048
   */
  botProof?: string;
}
