/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform routes accept Clerk `Authorization: Bearer` **or** the
  `ctx_platform_session` cookie (local/dev bridge). `POST /platform/auth/login`
  is disabled in production (HTTP 410) unless an explicit non-prod override
  is set.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
import type { CrmAiClassification } from "./crmAiClassification";
import type { CrmAuditEvent } from "./crmAuditEvent";
import type { CrmCompany } from "./crmCompany";
import type { CrmContact } from "./crmContact";
import type { CrmInquiry } from "./crmInquiry";
import type { CrmInquiryAnswer } from "./crmInquiryAnswer";
import type { CrmInquiryTagRef } from "./crmInquiryTagRef";
import type { CrmMeeting } from "./crmMeeting";
import type { CrmMessage } from "./crmMessage";
import type { CrmQualificationResult } from "./crmQualificationResult";
import type { CrmSlaInstance } from "./crmSlaInstance";
import type { CrmStaff } from "./crmStaff";
import type { CrmWorkflowExecution } from "./crmWorkflowExecution";

export interface CrmInquiryDetail {
  inquiry: CrmInquiry;
  contact: CrmContact;
  company: CrmCompany | null;
  assignee: CrmStaff | null;
  messages: CrmMessage[];
  answers: CrmInquiryAnswer[];
  qualification: CrmQualificationResult[];
  audit: CrmAuditEvent[];
  sla: CrmSlaInstance[];
  meetings: CrmMeeting[];
  ai: CrmAiClassification[];
  executions: CrmWorkflowExecution[];
  tags: CrmInquiryTagRef[];
}
