/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform routes accept Clerk `Authorization: Bearer` **or** the
  `ctx_platform_session` cookie (local/dev bridge). `POST /platform/auth/login`
  is disabled in production (HTTP 410) unless an explicit non-prod override
  is set.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
import type { CrmInquiryPriority } from "./crmInquiryPriority";
import type { CrmInquiryStatus } from "./crmInquiryStatus";
import type { CrmInquiryType } from "./crmInquiryType";
import type { CrmJsonMap } from "./crmJsonMap";
import type { CrmQualificationStatus } from "./crmQualificationStatus";

export interface CrmInquiry {
  id: string;
  reference: string;
  contactId: string;
  /** @nullable */
  companyId?: string | null;
  status: CrmInquiryStatus;
  priority: CrmInquiryPriority;
  source: string;
  channel: string;
  inquiryType: CrmInquiryType;
  useCaseKeys: string[];
  /** @nullable */
  useCaseOther?: string | null;
  /** @nullable */
  assignedTeamId?: string | null;
  /** @nullable */
  assignedStaffId?: string | null;
  /** @nullable */
  assignedReason?: string | null;
  qualificationStatus: CrmQualificationStatus;
  qualificationScore: number;
  /** @nullable */
  qualificationGrade?: string | null;
  /** @nullable */
  qualificationModelId?: string | null;
  /** @nullable */
  qualificationModelVersion?: number | null;
  /** @nullable */
  systemQualificationStatus?: string | null;
  /** @nullable */
  humanOverrideStatus?: string | null;
  /** @nullable */
  humanOverrideReason?: string | null;
  /** @nullable */
  humanOverrideBy?: string | null;
  /** @nullable */
  humanOverrideAt?: Date | null;
  /** @nullable */
  qualifiedAt?: Date | null;
  lastActivityAt: Date;
  /** @nullable */
  lastCustomerMessageAt?: Date | null;
  /** @nullable */
  firstResponseAt?: Date | null;
  /** @nullable */
  resolvedAt?: Date | null;
  /** @nullable */
  closedAt?: Date | null;
  /** @nullable */
  meetingOfferedAt?: Date | null;
  spamScore: number;
  /** @nullable */
  idempotencyKey?: string | null;
  attribution?: CrmJsonMap;
  createdAt: Date;
  updatedAt: Date;
}
