/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform routes accept Clerk `Authorization: Bearer` **or** the
  `ctx_platform_session` cookie (local/dev bridge). `POST /platform/auth/login`
  is disabled in production (HTTP 410) unless an explicit non-prod override
  is set.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
import type { CrmMeetingBookingStatus } from "./crmMeetingBookingStatus";

export interface CrmMeeting {
  id: string;
  /** @nullable */
  inquiryId?: string | null;
  /** @nullable */
  contactId?: string | null;
  /** @nullable */
  meetingTypeId?: string | null;
  /** @nullable */
  assignedStaffId?: string | null;
  /** @nullable */
  assignedTeamId?: string | null;
  bookingUrl: string;
  bookingStatus: CrmMeetingBookingStatus;
  /** @nullable */
  scheduledAt?: Date | null;
  /** @nullable */
  cancelledAt?: Date | null;
  /** @nullable */
  rescheduledAt?: Date | null;
  /** @nullable */
  externalBookingId?: string | null;
  /** @nullable */
  timezone?: string | null;
  createdAt: Date;
}
