/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform routes accept Clerk `Authorization: Bearer` **or** the
  `ctx_platform_session` cookie (local/dev bridge). `POST /platform/auth/login`
  is disabled in production (HTTP 410) unless an explicit non-prod override
  is set.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Values from PLATFORM_PERMISSIONS in lib/crm/rbac.ts
 */
export type CrmPlatformPermission =
  (typeof CrmPlatformPermission)[keyof typeof CrmPlatformPermission];

export const CrmPlatformPermission = {
  inquiriesview: "inquiries.view",
  inquiriesreply: "inquiries.reply",
  inquiriesforward: "inquiries.forward",
  inquiriesnote: "inquiries.note",
  inquiriesassign: "inquiries.assign",
  inquiriesstatus: "inquiries.status",
  inquiriespriority: "inquiries.priority",
  inquiriestags: "inquiries.tags",
  inquiriesqualificationoverride: "inquiries.qualification.override",
  inquirieslead_scoreview: "inquiries.lead_score.view",
  inquiriesexport: "inquiries.export",
  inquiriesdelete: "inquiries.delete",
  templatesmanage: "templates.manage",
  workflowsmanage: "workflows.manage",
  routingmanage: "routing.manage",
  slamanage: "sla.manage",
  meetingsmanage: "meetings.manage",
  analyticsview: "analytics.view",
  configmanage: "config.manage",
} as const;
