/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform (and Handler) routes use first-party ClaimTagX auth: the
  `ctx_auth_session` cookie (an opaque session/refresh token) **or** an
  opaque `Authorization: Bearer` token. No hosted identity provider is used.
  Sign in via `POST /platform/auth/login` (email + password); MFA, password
  reset, invitation acceptance and first-owner bootstrap are also
  first-party endpoints under `/platform/auth/*`.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
import type { InvitePlatformStaffBodyRole } from "./invitePlatformStaffBodyRole";

export type InvitePlatformStaffBody = {
  email: string;
  role?: InvitePlatformStaffBodyRole;
};
