/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform (and Handler) routes use first-party ClaimTagX auth: the
  `ctx_auth_session` cookie (an opaque session/refresh token) **or** an
  opaque `Authorization: Bearer` token. No hosted identity provider is used.
  Sign in via `POST /platform/auth/login` (email + password); MFA, password
  reset, invitation acceptance and first-owner bootstrap are also
  first-party endpoints under `/platform/auth/*`.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
import type { CrmInquiryStatus } from "./crmInquiryStatus";
import type { CrmQualificationStatus } from "./crmQualificationStatus";
import type { ListPlatformContactInquiriesDir } from "./listPlatformContactInquiriesDir";
import type { ListPlatformContactInquiriesReadState } from "./listPlatformContactInquiriesReadState";
import type { ListPlatformContactInquiriesSort } from "./listPlatformContactInquiriesSort";
import type { PageCursorParameter } from "./pageCursorParameter";
import type { PageLimitParameter } from "./pageLimitParameter";
import type { PageOffsetParameter } from "./pageOffsetParameter";

export type ListPlatformContactInquiriesParams = {
  /**
   * Inbox default 50, capped at 100.
   * @minimum 1
   * @maximum 100
   */
  limit?: PageLimitParameter;
  /**
   * Deprecated for `sort=createdAt` (keyset). Still accepted for score/lastActivityAt first-page offset only until those sorts gain cursors.
   * @minimum 0
   */
  offset?: PageOffsetParameter;
  /**
   * Opaque keyset cursor (createdAt + id). Forward page token from `nextCursor`.
   */
  cursor?: PageCursorParameter;
  /**
   * `score` sorts by `qualificationScore`.
   */
  sort?: ListPlatformContactInquiriesSort;
  dir?: ListPlatformContactInquiriesDir;
  status?: CrmInquiryStatus;
  qualificationStatus?: CrmQualificationStatus;
  /**
   * ISO 3166-1 alpha-2; compared uppercased.
   * @minLength 2
   * @maxLength 2
   */
  country?: string;
  assignedStaffId?: string;
  source?: string;
  /**
   * Inclusive lower bound on `createdAt` (`new Date(from)`).
   */
  from?: Date;
  /**
   * Inclusive upper bound on `createdAt` (`new Date(to)`).
   */
  to?: Date;
  /**
   * Case-insensitive substring on name, email, phone, company, or reference.
   */
  search?: string;
  readState?: ListPlatformContactInquiriesReadState;
  /**
   * Filter by inquiry type (e.g. sales, support).
   */
  inquiryType?: string;
  /**
   * Filter by origin channel (website, whatsapp, instagram, facebook, tiktok, x, linkedin, microsoft365).
   */
  channel?: string;
  priority?: string;
};
