import { Router, type IRouter } from "express";
import healthRouter from "./health";
import platformHealthRouter from "./platformHealth";
import assetsRouter from "./assets";
import meRouter from "./me";
import invitationsRouter from "./invitations";
import shiftsRouter from "./shifts";
import servicesRouter from "./services";
import messagesRouter from "./messages";
import intercomRouter from "./intercom";
import marketingRouter from "./marketing";
import contactRouter from "./contact";
import platformAuthRouter from "./platformAuth";
import platformContactRouter from "./platformContact";
import platformChannelsRouter from "./platformChannels";
import platformGovernanceRouter from "./platformGovernance";
import platformConfigChangesRouter from "./platformConfigChanges";
import platformEffectsRouter from "./platformEffects";
import platformMarketingRouter from "./platformMarketing";

const router: IRouter = Router();

router.use(healthRouter);
router.use(platformHealthRouter);
router.use(meRouter);
router.use(invitationsRouter);
router.use(shiftsRouter);
router.use(servicesRouter);
router.use(messagesRouter);
router.use(intercomRouter);
router.use(assetsRouter);
router.use(marketingRouter);
router.use(contactRouter);
router.use(platformAuthRouter);
router.use(platformContactRouter);
router.use(platformChannelsRouter);
router.use(platformGovernanceRouter);
router.use(platformConfigChangesRouter);
router.use(platformEffectsRouter);
router.use(platformMarketingRouter);

export default router;
