/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * OpenAPI 3.1 fragment for ClaimTagX public Contact Us and Platform Contact
Operations. Paths are relative to the same `/api` server as `openapi.yaml`.

**Auth**
- Public `/contact/*` form endpoints are unauthenticated.
- Inbound webhooks use `X-Webhook-Secret`.
- Platform routes accept Clerk `Authorization: Bearer` **or** the
  `ctx_platform_session` cookie (local/dev bridge). `POST /platform/auth/login`
  is disabled in production (HTTP 410) unless an explicit non-prod override
  is set.

**Permissions**
Platform operations declare `x-permission` matching `PLATFORM_PERMISSIONS`
in `artifacts/api-server/src/lib/crm/rbac.ts`. `GET /platform/me` requires
an authenticated staff session but no specific permission.

**Status**
Live handlers are `x-status: implemented`. Remaining stubs are
`x-status: planned`.

 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns country options, optional IP-detected country (`CF-IPCountry`),
current terms/privacy versions, message max length, and active taxonomy.
Falls back to built-in taxonomy if the database is unavailable.

 * @summary Bootstrap the public contact form
 */
export const getContactBootstrapHeaderCFIPCountryMin = 2;
export const getContactBootstrapHeaderCFIPCountryMax = 2;

export const GetContactBootstrapHeader = zod.object({
  "CF-IPCountry": zod
    .string()
    .min(getContactBootstrapHeaderCFIPCountryMin)
    .max(getContactBootstrapHeaderCFIPCountryMax)
    .optional()
    .describe("Cloudflare country code. `XX` and `T1` are ignored."),
});

export const GetContactBootstrapResponse = zod.object({
  countries: zod.array(
    zod.object({
      code: zod.string(),
      name: zod.string(),
      callingCode: zod.string().describe("E.164 calling prefix including `+`"),
    }),
  ),
  detectedCountry: zod.string().nullable(),
  countryDetectionSource: zod.enum(["ip", "none"]),
  termsVersion: zod.string(),
  privacyPolicyVersion: zod.string(),
  messageMaxLength: zod.number(),
  taxonomy: zod.array(
    zod.object({
      id: zod.string(),
      kind: zod.string(),
      key: zod.string(),
      parentKey: zod.string(),
      label: zod.string(),
      description: zod.string().nullish(),
      sortOrder: zod.number(),
      active: zod.boolean(),
      metadata: zod.record(zod.string(), zod.unknown()).optional(),
    }),
  ),
  botProtection: zod
    .object({
      provider: zod.string().optional(),
      siteKey: zod
        .string()
        .optional()
        .describe("Public Turnstile site key. Never a secret."),
      scriptSrc: zod.string().optional(),
      action: zod.string().optional(),
      fallback: zod.enum(["email"]).optional(),
      proofRequired: zod.boolean().optional(),
    })
    .optional(),
});

/**
 * Validates and persists a contact inquiry. Idempotent on `idempotencyKey`
(UUID in the body): a replay returns the original reference without a
second insert. Rate-limited to 8 submissions per IP per 10 minutes.
Sales inquiries require at least one `useCaseKeys` entry.

 * @summary Submit a public contact inquiry
 */
export const SubmitContactInquiryHeader = zod.object({
  "X-Request-Id": zod
    .string()
    .optional()
    .describe(
      "Correlation id echoed on public submit responses. Generated if omitted.",
    ),
  "Idempotency-Key": zod
    .string()
    .uuid()
    .optional()
    .describe(
      "Recommended client header for retry-safe writes. Public submit currently\nrequires the same UUID in the JSON body field `idempotencyKey`; the\nserver does not read this header yet. Planned DSAR export should honor it.\n",
    ),
});

export const submitContactInquiryBodyFirstNameMax = 80;

export const submitContactInquiryBodyLastNameMax = 80;

export const submitContactInquiryBodyJobTitleMax = 120;

export const submitContactInquiryBodyCompanyNameMax = 160;

export const submitContactInquiryBodyEmailMax = 254;

export const submitContactInquiryBodyCountryMin = 2;
export const submitContactInquiryBodyCountryMax = 2;

export const submitContactInquiryBodyPhoneRawMin = 4;
export const submitContactInquiryBodyPhoneRawMax = 32;

export const submitContactInquiryBodyUseCaseKeysItemMax = 64;

export const submitContactInquiryBodyUseCaseKeysDefault = [];
export const submitContactInquiryBodyUseCaseKeysMax = 12;

export const submitContactInquiryBodyUseCaseOtherMax = 160;

export const submitContactInquiryBodyMessageMin = 10;
export const submitContactInquiryBodyMessageMax = 8000;

export const submitContactInquiryBodyAnswersOptionKeysItemMax = 64;

export const submitContactInquiryBodyAnswersOptionKeysMax = 20;

export const submitContactInquiryBodyAnswersFreeTextMax = 2000;

export const submitContactInquiryBodyLocaleMax = 32;

export const submitContactInquiryBodyHoneypotMax = 200;

export const submitContactInquiryBodyBotProofMax = 2048;

export const SubmitContactInquiryBody = zod.object({
  firstName: zod.string().min(1).max(submitContactInquiryBodyFirstNameMax),
  lastName: zod.string().min(1).max(submitContactInquiryBodyLastNameMax),
  jobTitle: zod.string().min(1).max(submitContactInquiryBodyJobTitleMax),
  companyName: zod.string().min(1).max(submitContactInquiryBodyCompanyNameMax),
  email: zod.string().email().max(submitContactInquiryBodyEmailMax),
  country: zod
    .string()
    .min(submitContactInquiryBodyCountryMin)
    .max(submitContactInquiryBodyCountryMax)
    .describe("ISO 3166-1 alpha-2"),
  phoneRaw: zod
    .string()
    .min(submitContactInquiryBodyPhoneRawMin)
    .max(submitContactInquiryBodyPhoneRawMax),
  inquiryType: zod.enum(["sales", "general", "technical", "billing", "other"]),
  useCaseKeys: zod
    .array(zod.string().min(1).max(submitContactInquiryBodyUseCaseKeysItemMax))
    .max(submitContactInquiryBodyUseCaseKeysMax)
    .default(submitContactInquiryBodyUseCaseKeysDefault)
    .describe("Required (min 1) when `inquiryType` is `sales`."),
  useCaseOther: zod
    .string()
    .max(submitContactInquiryBodyUseCaseOtherMax)
    .optional(),
  message: zod
    .string()
    .min(submitContactInquiryBodyMessageMin)
    .max(submitContactInquiryBodyMessageMax),
  answers: zod
    .record(
      zod.string(),
      zod.object({
        optionKeys: zod
          .array(
            zod.string().max(submitContactInquiryBodyAnswersOptionKeysItemMax),
          )
          .max(submitContactInquiryBodyAnswersOptionKeysMax)
          .optional(),
        freeText: zod
          .string()
          .max(submitContactInquiryBodyAnswersFreeTextMax)
          .optional(),
      }),
    )
    .optional(),
  termsAccepted: zod.boolean(),
  locale: zod.string().max(submitContactInquiryBodyLocaleMax).optional(),
  attribution: zod.record(zod.string(), zod.unknown()).optional(),
  idempotencyKey: zod
    .string()
    .uuid()
    .describe("Required. Replays return the original inquiry."),
  honeypot: zod
    .string()
    .max(submitContactInquiryBodyHoneypotMax)
    .optional()
    .describe("Must be empty; any value yields HTTP 400."),
  botProof: zod
    .string()
    .max(submitContactInquiryBodyBotProofMax)
    .optional()
    .describe(
      "Provider proof token (Turnstile). Required when bootstrap.botProtection.proofRequired is true. Sent only over HTTPS in production.",
    ),
});

/**
 * Matches `CTX-YYYY-NNNNNN` in the subject. Unmatched payloads return
202 `{ matched: false }`. Production requires `CONTACT_INBOUND_WEBHOOK_SECRET`
and rejects unsigned requests with 503 when the secret is unset.

 * @summary Attach an inbound customer email to an inquiry
 */
export const InboundContactEmailWebhookHeader = zod.object({
  "X-Webhook-Secret": zod
    .string()
    .optional()
    .describe(
      "Required when the corresponding `CONTACT_\*_WEBHOOK_SECRET` env is set.",
    ),
});

export const inboundContactEmailWebhookBodySubjectMax = 500;

export const inboundContactEmailWebhookBodyTextMax = 20000;

export const inboundContactEmailWebhookBodyMessageIdMax = 200;

export const inboundContactEmailWebhookBodyInReplyToMax = 200;

export const InboundContactEmailWebhookBody = zod.object({
  from: zod.string().email(),
  subject: zod
    .string()
    .max(inboundContactEmailWebhookBodySubjectMax)
    .optional(),
  text: zod.string().min(1).max(inboundContactEmailWebhookBodyTextMax),
  messageId: zod
    .string()
    .max(inboundContactEmailWebhookBodyMessageIdMax)
    .optional(),
  inReplyTo: zod
    .string()
    .max(inboundContactEmailWebhookBodyInReplyToMax)
    .optional(),
});

export const InboundContactEmailWebhookResponse = zod.object({
  matched: zod.boolean(),
  reference: zod.string().optional(),
});

/**
 * Production inbound mailbox webhook. Graph subscription validation echoes
`validationToken` as `text/plain`. Change notifications are authorized via
subscription `clientState` (not `X-Webhook-Secret`). Returns 202 when accepted.

 * @summary Microsoft Graph mail change notifications
 */
export const MicrosoftGraphMailWebhookQueryParams = zod.object({
  validationToken: zod.coerce
    .string()
    .optional()
    .describe("Graph subscription validation handshake token"),
});

export const MicrosoftGraphMailWebhookBody = zod.object({
  value: zod.array(zod.record(zod.string(), zod.unknown())).optional(),
});

/**
 * Resolves an inquiry by `reference` or latest inquiry for `email`.
When `CONTACT_SCHEDULING_WEBHOOK_SECRET` is set, `X-Webhook-Secret` must match.

 * @summary Update meeting booking status from an external scheduler
 */
export const SchedulingContactWebhookHeader = zod.object({
  "X-Webhook-Secret": zod
    .string()
    .optional()
    .describe(
      "Required when the corresponding `CONTACT_\*_WEBHOOK_SECRET` env is set.",
    ),
});

export const SchedulingContactWebhookBody = zod.object({
  reference: zod.string().optional(),
  email: zod.string().email().optional(),
  scheduledAt: zod.coerce.date().optional(),
  externalBookingId: zod.string().optional(),
  status: zod
    .enum([
      "INVITED",
      "BOOKED",
      "CANCELLED",
      "RESCHEDULED",
      "NO_SHOW",
      "COMPLETED",
    ])
    .optional(),
});

export const SchedulingContactWebhookResponse = zod.object({
  matched: zod.boolean(),
  reference: zod.string().optional(),
});

/**
 * Provider hub challenge handshake. Not a browser client. Signature and
subscribe token are server-controlled. Not LIVE_VERIFIED without an
approved Meta WhatsApp round trip.

 * @summary WhatsApp Cloud API webhook verification
 */
export const WhatsappContactWebhookGetQueryParams = zod.object({
  "hub.mode": zod.coerce.string().optional(),
  "hub.verify_token": zod.coerce.string().optional(),
  "hub.challenge": zod.coerce.string().optional(),
});

/**
 * HMAC-verified inbound events. Returns 401/403 on signature failure.
Not LIVE_VERIFIED from local HMAC fixtures.

 * @summary WhatsApp Cloud API inbound webhook
 */
export const WhatsappContactWebhookBody = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * Provider hub challenge handshake. Not LIVE_VERIFIED without Meta app review.
 * @summary Meta Messenger/Instagram webhook verification
 */
export const MetaContactWebhookGetQueryParams = zod.object({
  "hub.mode": zod.coerce.string().optional(),
  "hub.verify_token": zod.coerce.string().optional(),
  "hub.challenge": zod.coerce.string().optional(),
});

/**
 * HMAC-verified inbound events. Instagram vs Messenger is selected from payload object.
 * @summary Meta Messenger/Instagram inbound webhook
 */
export const MetaContactWebhookBody = zod.record(zod.string(), zod.unknown());

/**
 * CRC token handshake. Not LIVE_VERIFIED without X developer approval.
 * @summary X (Twitter) Account Activity webhook verification
 */
export const XContactWebhookGetQueryParams = zod.object({
  crc_token: zod.coerce.string().optional(),
});

export const XContactWebhookGetResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * Signature-verified inbound events. Not LIVE_VERIFIED from local fixtures.
 * @summary X (Twitter) Account Activity inbound webhook
 */
export const XContactWebhookBody = zod.record(zod.string(), zod.unknown());

/**
 * Mints `ctx_platform_session` after validating `PLATFORM_STAFF_ACCESS_KEY`.
Returns **410** unless `PLATFORM_ALLOW_ACCESS_KEY_LOGIN=true` and
`NODE_ENV` is not `production`. Production staff must use Clerk.

 * @summary Dev-only shared access-key login
 */
export const platformAuthLoginBodyAccessKeyMin = 8;
export const platformAuthLoginBodyAccessKeyMax = 200;

export const platformAuthLoginBodyNameMax = 120;

export const PlatformAuthLoginBody = zod.object({
  email: zod.string().email(),
  accessKey: zod
    .string()
    .min(platformAuthLoginBodyAccessKeyMin)
    .max(platformAuthLoginBodyAccessKeyMax),
  name: zod.string().max(platformAuthLoginBodyNameMax).optional(),
});

export const PlatformAuthLoginResponse = zod.object({
  id: zod.string().uuid(),
  email: zod.string().email(),
  name: zod.string(),
  role: zod.enum(["owner", "admin", "sales", "operator", "analyst"]),
  permissions: zod.array(
    zod
      .enum([
        "inquiries.view",
        "inquiries.reply",
        "inquiries.forward",
        "inquiries.note",
        "inquiries.assign",
        "inquiries.status",
        "inquiries.priority",
        "inquiries.tags",
        "inquiries.qualification.override",
        "inquiries.lead_score.view",
        "inquiries.export",
        "inquiries.delete",
        "templates.manage",
        "workflows.manage",
        "routing.manage",
        "sla.manage",
        "meetings.manage",
        "analytics.view",
        "config.manage",
      ])
      .describe("Values from PLATFORM_PERMISSIONS in lib\/crm\/rbac.ts"),
  ),
});

/**
 * @summary Current authenticated platform staff
 */
export const GetPlatformMeResponse = zod.object({
  id: zod.string().uuid(),
  email: zod.string().email(),
  name: zod.string(),
  role: zod.enum(["owner", "admin", "sales", "operator", "analyst"]),
  permissions: zod.array(
    zod
      .enum([
        "inquiries.view",
        "inquiries.reply",
        "inquiries.forward",
        "inquiries.note",
        "inquiries.assign",
        "inquiries.status",
        "inquiries.priority",
        "inquiries.tags",
        "inquiries.qualification.override",
        "inquiries.lead_score.view",
        "inquiries.export",
        "inquiries.delete",
        "templates.manage",
        "workflows.manage",
        "routing.manage",
        "sla.manage",
        "meetings.manage",
        "analytics.view",
        "config.manage",
      ])
      .describe("Values from PLATFORM_PERMISSIONS in lib\/crm\/rbac.ts"),
  ),
});

/**
 * Honest connector status. Simulators and local HMAC fixtures are never LIVE_VERIFIED.

 * @summary Channel health snapshot
 */
export const ListPlatformContactChannelsResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary Refresh persisted channel health
 */
export const RefreshPlatformContactChannelsHealthResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary List channel identities for a contact
 */
export const ListPlatformContactIdentitiesQueryParams = zod.object({
  contactId: zod.coerce.string().uuid(),
});

export const ListPlatformContactIdentitiesResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary Link a channel identity to a contact
 */
export const LinkPlatformContactIdentityParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const LinkPlatformContactIdentityBody = zod.object({
  contactId: zod.string().uuid(),
});

/**
 * @summary Unlink a channel identity from a contact
 */
export const UnlinkPlatformContactIdentityParams = zod.object({
  id: zod.coerce.string().uuid(),
});

/**
 * @summary Retry a failed outbound channel message
 */
export const RetryPlatformContactMessageParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const RetryPlatformContactMessageResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary List staff and teams
 */
export const ListPlatformContactStaffResponse = zod.object({
  staff: zod.array(
    zod.object({
      id: zod.string().uuid(),
      clerkUserId: zod.string().nullish(),
      email: zod.string(),
      emailNormalized: zod.string(),
      name: zod.string(),
      role: zod.string(),
      permissions: zod.array(zod.string()),
      teamId: zod.string().uuid().nullish(),
      status: zod.string(),
      lastLoginAt: zod.coerce.date().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  teams: zod.array(
    zod.object({
      id: zod.string().uuid(),
      slug: zod.string(),
      name: zod.string(),
      region: zod.string().nullish(),
      roundRobinCursor: zod.number(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * Joins contact, company, assignee, first-response SLA, and the calling
staff member's read cursor. `total` is the SQL count **before** the
in-memory `readState` filter.

 * @summary Paginated inbox of inquiries
 */
export const listPlatformContactInquiriesQueryLimitDefault = 50;
export const listPlatformContactInquiriesQueryLimitMax = 100;

export const listPlatformContactInquiriesQueryOffsetDefault = 0;
export const listPlatformContactInquiriesQueryOffsetMin = 0;

export const listPlatformContactInquiriesQuerySortDefault = `createdAt`;
export const listPlatformContactInquiriesQueryDirDefault = `desc`;
export const listPlatformContactInquiriesQueryCountryMin = 2;
export const listPlatformContactInquiriesQueryCountryMax = 2;

export const ListPlatformContactInquiriesQueryParams = zod.object({
  limit: zod.coerce
    .number()
    .min(1)
    .max(listPlatformContactInquiriesQueryLimitMax)
    .default(listPlatformContactInquiriesQueryLimitDefault)
    .describe("Inbox default 50, capped at 100."),
  offset: zod.coerce
    .number()
    .min(listPlatformContactInquiriesQueryOffsetMin)
    .default(listPlatformContactInquiriesQueryOffsetDefault)
    .describe(
      "Deprecated for `sort=createdAt` (keyset). Still accepted for score\/lastActivityAt first-page offset only until those sorts gain cursors.",
    ),
  cursor: zod.coerce
    .string()
    .optional()
    .describe(
      "Opaque keyset cursor (createdAt + id). Forward page token from `nextCursor`.",
    ),
  sort: zod
    .enum(["createdAt", "lastActivityAt", "score"])
    .default(listPlatformContactInquiriesQuerySortDefault)
    .describe("`score` sorts by `qualificationScore`."),
  dir: zod
    .enum(["asc", "desc"])
    .default(listPlatformContactInquiriesQueryDirDefault),
  status: zod
    .enum([
      "NEW",
      "TRIAGED",
      "ASSIGNED",
      "IN_PROGRESS",
      "WAITING_FOR_CUSTOMER",
      "WAITING_INTERNAL",
      "RESOLVED",
      "CLOSED",
      "SPAM",
      "DUPLICATE",
      "CANCELLED",
    ])
    .optional(),
  qualificationStatus: zod
    .enum([
      "UNASSESSED",
      "UNQUALIFIED",
      "MARKETING_QUALIFIED",
      "SALES_QUALIFIED",
      "HIGH_PRIORITY",
      "DISQUALIFIED",
    ])
    .optional(),
  country: zod.coerce
    .string()
    .min(listPlatformContactInquiriesQueryCountryMin)
    .max(listPlatformContactInquiriesQueryCountryMax)
    .optional()
    .describe("ISO 3166-1 alpha-2; compared uppercased."),
  assignedStaffId: zod.coerce.string().uuid().optional(),
  source: zod.coerce.string().optional(),
  from: zod
    .date()
    .optional()
    .describe("Inclusive lower bound on `createdAt` (`new Date(from)`)."),
  to: zod
    .date()
    .optional()
    .describe("Inclusive upper bound on `createdAt` (`new Date(to)`)."),
  search: zod.coerce
    .string()
    .optional()
    .describe(
      "Case-insensitive substring on name, email, phone, company, or reference.",
    ),
  readState: zod.enum(["unread", "read"]).optional(),
  inquiryType: zod.coerce
    .string()
    .optional()
    .describe("Filter by inquiry type (e.g. sales, support)."),
  channel: zod.coerce
    .string()
    .optional()
    .describe(
      "Filter by origin channel (website, whatsapp, instagram, facebook, tiktok, x, linkedin, microsoft365).",
    ),
  priority: zod.coerce.string().optional(),
});

export const ListPlatformContactInquiriesResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      reference: zod.string(),
      createdAt: zod.coerce.date(),
      lastActivityAt: zod.coerce.date(),
      firstName: zod.string(),
      lastName: zod.string(),
      company: zod.string(),
      jobTitle: zod.string(),
      country: zod.string(),
      useCase: zod.array(zod.string()),
      qualificationStatus: zod.enum([
        "UNASSESSED",
        "UNQUALIFIED",
        "MARKETING_QUALIFIED",
        "SALES_QUALIFIED",
        "HIGH_PRIORITY",
        "DISQUALIFIED",
      ]),
      leadScore: zod.number(),
      assignedTo: zod.string().nullable(),
      assignedStaffId: zod.string().uuid().nullable(),
      status: zod.enum([
        "NEW",
        "TRIAGED",
        "ASSIGNED",
        "IN_PROGRESS",
        "WAITING_FOR_CUSTOMER",
        "WAITING_INTERNAL",
        "RESOLVED",
        "CLOSED",
        "SPAM",
        "DUPLICATE",
        "CANCELLED",
      ]),
      unread: zod.boolean(),
      slaStatus: zod.string().nullable(),
      slaDueAt: zod.coerce.date().nullable(),
      hasMeeting: zod
        .boolean()
        .describe("Always `false` in the current list handler."),
    }),
  ),
  total: zod
    .number()
    .describe(
      "Count of rows matching SQL filters (before in-memory readState).",
    ),
  limit: zod.number(),
  offset: zod
    .number()
    .describe("Always 0 when keyset pagination is used (`sort=createdAt`)."),
  nextCursor: zod
    .string()
    .nullish()
    .describe("Opaque forward cursor. Null when this is the last page."),
  cursor: zod.string().nullish(),
});

/**
 * @summary Mark many inquiries read or unread for the current staff
 */
export const bulkMarkPlatformInquiriesReadBodyIdsMax = 100;

export const BulkMarkPlatformInquiriesReadBody = zod.object({
  ids: zod
    .array(zod.string().uuid())
    .min(1)
    .max(bulkMarkPlatformInquiriesReadBodyIdsMax),
  unread: zod.boolean().optional(),
});

/**
 * Returns the inquiry plus related contact, company, assignee, visible
messages (`customer` | `internal`), answers, qualification results,
per-inquiry audit (80 newest), SLA instances, meetings, AI rows,
workflow executions, and tags. Marks the inquiry read for the caller
and writes `inquiry.opened` to the audit log.

 * @summary Inquiry workspace (detail)
 */
export const GetPlatformContactInquiryParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const GetPlatformContactInquiryResponse = zod.object({
  inquiry: zod.object({
    id: zod.string().uuid(),
    reference: zod.string(),
    contactId: zod.string().uuid(),
    companyId: zod.string().uuid().nullish(),
    status: zod.enum([
      "NEW",
      "TRIAGED",
      "ASSIGNED",
      "IN_PROGRESS",
      "WAITING_FOR_CUSTOMER",
      "WAITING_INTERNAL",
      "RESOLVED",
      "CLOSED",
      "SPAM",
      "DUPLICATE",
      "CANCELLED",
    ]),
    priority: zod.enum(["low", "normal", "high", "urgent"]),
    source: zod.string(),
    channel: zod.string(),
    inquiryType: zod.enum([
      "sales",
      "general",
      "technical",
      "billing",
      "other",
    ]),
    useCaseKeys: zod.array(zod.string()),
    useCaseOther: zod.string().nullish(),
    assignedTeamId: zod.string().uuid().nullish(),
    assignedStaffId: zod.string().uuid().nullish(),
    assignedReason: zod.string().nullish(),
    qualificationStatus: zod.enum([
      "UNASSESSED",
      "UNQUALIFIED",
      "MARKETING_QUALIFIED",
      "SALES_QUALIFIED",
      "HIGH_PRIORITY",
      "DISQUALIFIED",
    ]),
    qualificationScore: zod.number(),
    qualificationGrade: zod.string().nullish(),
    qualificationModelId: zod.string().uuid().nullish(),
    qualificationModelVersion: zod.number().nullish(),
    systemQualificationStatus: zod.string().nullish(),
    humanOverrideStatus: zod.string().nullish(),
    humanOverrideReason: zod.string().nullish(),
    humanOverrideBy: zod.string().uuid().nullish(),
    humanOverrideAt: zod.coerce.date().nullish(),
    qualifiedAt: zod.coerce.date().nullish(),
    lastActivityAt: zod.coerce.date(),
    lastCustomerMessageAt: zod.coerce.date().nullish(),
    firstResponseAt: zod.coerce.date().nullish(),
    resolvedAt: zod.coerce.date().nullish(),
    closedAt: zod.coerce.date().nullish(),
    meetingOfferedAt: zod.coerce.date().nullish(),
    spamScore: zod.number(),
    idempotencyKey: zod.string().nullish(),
    attribution: zod.record(zod.string(), zod.unknown()).optional(),
    createdAt: zod.coerce.date(),
    updatedAt: zod.coerce.date(),
  }),
  contact: zod.object({
    id: zod.string().uuid(),
    companyId: zod.string().uuid().nullish(),
    firstName: zod.string(),
    lastName: zod.string(),
    jobTitle: zod.string(),
    email: zod.string(),
    emailNormalized: zod.string(),
    country: zod.string(),
    phoneRaw: zod.string().nullish(),
    phoneCountry: zod.string().nullish(),
    phoneCountryCallingCode: zod.string().nullish(),
    phoneNationalNumber: zod.string().nullish(),
    phoneE164: zod.string().nullish(),
    phoneValidationStatus: zod.string().nullish(),
    phoneType: zod.string().nullish(),
    locale: zod.string().nullish(),
    lifecycleStage: zod.string(),
    createdAt: zod.coerce.date(),
    updatedAt: zod.coerce.date(),
  }),
  company: zod.union([
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      nameNormalized: zod.string(),
      country: zod.string().nullish(),
      website: zod.string().nullish(),
      createdAt: zod.coerce.date(),
      updatedAt: zod.coerce.date(),
    }),
    zod.null(),
  ]),
  assignee: zod.union([
    zod.object({
      id: zod.string().uuid(),
      clerkUserId: zod.string().nullish(),
      email: zod.string(),
      emailNormalized: zod.string(),
      name: zod.string(),
      role: zod.string(),
      permissions: zod.array(zod.string()),
      teamId: zod.string().uuid().nullish(),
      status: zod.string(),
      lastLoginAt: zod.coerce.date().nullish(),
      createdAt: zod.coerce.date(),
    }),
    zod.null(),
  ]),
  messages: zod.array(
    zod.object({
      id: zod.string().uuid(),
      conversationId: zod.string().uuid(),
      inquiryId: zod.string().uuid(),
      kind: zod.string(),
      visibility: zod.enum(["customer", "internal"]),
      channel: zod.string(),
      authorType: zod.string(),
      authorStaffId: zod.string().uuid().nullish(),
      authorContactId: zod.string().uuid().nullish(),
      subject: zod.string().nullish(),
      body: zod.string(),
      bodyHtml: zod.string().nullish(),
      templateId: zod.string().uuid().nullish(),
      templateVersionId: zod.string().uuid().nullish(),
      externalMessageId: zod.string().nullish(),
      inReplyTo: zod.string().nullish(),
      forwardedTo: zod.string().nullish(),
      mentions: zod.array(zod.string()),
      metadata: zod.record(zod.string(), zod.unknown()).optional(),
      createdAt: zod.coerce.date(),
    }),
  ),
  answers: zod.array(
    zod.object({
      id: zod.string().uuid(),
      inquiryId: zod.string().uuid(),
      questionKey: zod.string(),
      optionKeys: zod.array(zod.string()),
      freeText: zod.string().nullish(),
    }),
  ),
  qualification: zod.array(
    zod.object({
      id: zod.string().uuid(),
      inquiryId: zod.string().uuid(),
      modelId: zod.string().uuid().nullish(),
      modelVersion: zod.number(),
      score: zod.number(),
      grade: zod.string().nullish(),
      status: zod.string(),
      reasons: zod.array(zod.record(zod.string(), zod.unknown())),
      source: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
  audit: zod.array(
    zod.object({
      id: zod.string().uuid(),
      actorType: zod.string(),
      actorId: zod.string().nullish(),
      action: zod.string(),
      entityType: zod.string(),
      entityId: zod.string(),
      inquiryId: zod.string().uuid().nullish(),
      contactId: zod.string().uuid().nullish(),
      beforeValue: zod.record(zod.string(), zod.unknown()).optional(),
      afterValue: zod.record(zod.string(), zod.unknown()).optional(),
      workflowId: zod.string().uuid().nullish(),
      correlationId: zod.string().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  sla: zod.array(
    zod.object({
      id: zod.string().uuid(),
      inquiryId: zod.string().uuid(),
      policyId: zod.string().uuid(),
      policyVersion: zod.number(),
      measure: zod.string(),
      dueAt: zod.coerce.date(),
      status: zod.enum(["ON_TRACK", "AT_RISK", "BREACHED", "COMPLETED"]),
      completedAt: zod.coerce.date().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  meetings: zod.array(
    zod.object({
      id: zod.string().uuid(),
      inquiryId: zod.string().uuid().nullish(),
      contactId: zod.string().uuid().nullish(),
      meetingTypeId: zod.string().uuid().nullish(),
      assignedStaffId: zod.string().uuid().nullish(),
      assignedTeamId: zod.string().uuid().nullish(),
      bookingUrl: zod.string(),
      bookingStatus: zod.enum([
        "INVITED",
        "BOOKED",
        "CANCELLED",
        "RESCHEDULED",
        "NO_SHOW",
        "COMPLETED",
      ]),
      scheduledAt: zod.coerce.date().nullish(),
      cancelledAt: zod.coerce.date().nullish(),
      rescheduledAt: zod.coerce.date().nullish(),
      externalBookingId: zod.string().nullish(),
      timezone: zod.string().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  ai: zod.array(
    zod.object({
      id: zod.string().uuid(),
      inquiryId: zod.string().uuid(),
      provider: zod.string(),
      model: zod.string().nullish(),
      confidence: zod.number().nullish(),
      output: zod.record(zod.string(), zod.unknown()),
      createdAt: zod.coerce.date(),
    }),
  ),
  executions: zod.array(
    zod.object({
      id: zod.string().uuid(),
      workflowId: zod.string().uuid(),
      workflowVersion: zod.number(),
      inquiryId: zod.string().uuid().nullish(),
      trigger: zod.string(),
      matched: zod.record(zod.string(), zod.unknown()).optional(),
      status: zod.string(),
      error: zod.string().nullish(),
      idempotencyKey: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
  tags: zod.array(
    zod.object({
      id: zod.string().uuid(),
      slug: zod.string(),
      label: zod.string(),
    }),
  ),
});

/**
 * @summary Mark one inquiry read or unread for the current staff
 */
export const MarkPlatformInquiryReadParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const MarkPlatformInquiryReadBody = zod.object({
  unread: zod
    .boolean()
    .optional()
    .describe("When true, clears the staff read cursor."),
});

/**
 * Emails the contact and inserts a `staff_reply` message. Optional
`templateKey` renders the latest template version. Sets status to
`WAITING_FOR_CUSTOMER` and completes first-response SLA when this is
the first staff reply.

 * @summary Send a customer-visible staff reply
 */
export const ReplyPlatformInquiryParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const replyPlatformInquiryBodyBodyMax = 8000;

export const ReplyPlatformInquiryBody = zod.object({
  body: zod.string().min(1).max(replyPlatformInquiryBodyBodyMax),
  templateKey: zod.string().optional(),
  expectedUpdatedAt: zod.coerce
    .date()
    .optional()
    .describe("Optimistic concurrency token from the inquiry updatedAt."),
});

/**
 * @summary Add an internal note (supports @mentions)
 */
export const AddPlatformInquiryNoteParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const addPlatformInquiryNoteBodyBodyMax = 8000;

export const AddPlatformInquiryNoteBody = zod.object({
  body: zod.string().min(1).max(addPlatformInquiryNoteBodyBodyMax),
  expectedUpdatedAt: zod.coerce.date().optional(),
});

/**
 * @summary Forward the customer-visible thread by email
 */
export const ForwardPlatformInquiryParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const forwardPlatformInquiryBodyNoteMax = 2000;

export const ForwardPlatformInquiryBody = zod.object({
  to: zod.string().email(),
  note: zod.string().max(forwardPlatformInquiryBodyNoteMax).optional(),
  expectedUpdatedAt: zod.coerce.date().optional(),
});

/**
 * @summary Manually assign or unassign staff / team
 */
export const AssignPlatformInquiryParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const AssignPlatformInquiryBody = zod.object({
  staffId: zod.string().uuid().nullish(),
  teamId: zod.string().uuid().nullish(),
});

export const AssignPlatformInquiryResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary Change inquiry status
 */
export const SetPlatformInquiryStatusParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const SetPlatformInquiryStatusBody = zod.object({
  status: zod.enum([
    "NEW",
    "TRIAGED",
    "ASSIGNED",
    "IN_PROGRESS",
    "WAITING_FOR_CUSTOMER",
    "WAITING_INTERNAL",
    "RESOLVED",
    "CLOSED",
    "SPAM",
    "DUPLICATE",
    "CANCELLED",
  ]),
});

export const SetPlatformInquiryStatusResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary Change inquiry priority
 */
export const SetPlatformInquiryPriorityParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const SetPlatformInquiryPriorityBody = zod.object({
  priority: zod.enum(["low", "normal", "high", "urgent"]),
});

export const SetPlatformInquiryPriorityResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary Attach a tag by slug
 */
export const AddPlatformInquiryTagParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const addPlatformInquiryTagBodySlugMax = 40;

export const AddPlatformInquiryTagBody = zod.object({
  slug: zod.string().min(1).max(addPlatformInquiryTagBodySlugMax),
});

export const AddPlatformInquiryTagResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary Human override of qualification status
 */
export const OverridePlatformInquiryQualificationParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const overridePlatformInquiryQualificationBodyReasonMin = 3;
export const overridePlatformInquiryQualificationBodyReasonMax = 500;

export const OverridePlatformInquiryQualificationBody = zod.object({
  status: zod.enum([
    "UNASSESSED",
    "UNQUALIFIED",
    "MARKETING_QUALIFIED",
    "SALES_QUALIFIED",
    "HIGH_PRIORITY",
    "DISQUALIFIED",
  ]),
  reason: zod
    .string()
    .min(overridePlatformInquiryQualificationBodyReasonMin)
    .max(overridePlatformInquiryQualificationBodyReasonMax),
});

export const OverridePlatformInquiryQualificationResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary Generate / persist an external meeting booking URL
 */
export const GeneratePlatformInquiryMeetingParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const GeneratePlatformInquiryMeetingResponse = zod.object({
  bookingUrl: zod.string(),
});

/**
 * @summary Convert an inquiry into a sales opportunity (qualification + audit)
 */
export const ConvertPlatformInquiryLeadParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ConvertPlatformInquiryLeadBody = zod.object({
  opportunityName: zod.string().optional(),
  note: zod.string().optional(),
});

/**
 * Runs seeded actions such as `generate_meeting`, `send_template`,
`change_status`, and `add_tag`.

 * @summary Execute a named macro against the inquiry
 */
export const RunPlatformInquiryMacroParams = zod.object({
  id: zod.coerce.string().uuid(),
  key: zod.coerce.string().describe("Macro key (e.g. `SEND_MEETING_REQUEST`)"),
});

export const RunPlatformInquiryMacroResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary List templates and all versions
 */
export const ListPlatformContactTemplatesResponse = zod.object({
  templates: zod.array(
    zod.object({
      id: zod.string().uuid(),
      key: zod.string(),
      internalName: zod.string(),
      description: zod.string().nullish(),
      category: zod.string(),
      channel: zod.string(),
      status: zod.string(),
      createdBy: zod.string().uuid().nullish(),
      updatedBy: zod.string().uuid().nullish(),
      publishedAt: zod.coerce.date().nullish(),
      archivedAt: zod.coerce.date().nullish(),
      createdAt: zod.coerce.date(),
      updatedAt: zod.coerce.date(),
    }),
  ),
  versions: zod.array(
    zod.object({
      id: zod.string().uuid(),
      templateId: zod.string().uuid(),
      versionNumber: zod.number(),
      language: zod.string(),
      subject: zod.string(),
      body: zod.string(),
      changeSummary: zod.string().nullish(),
      changedBy: zod.string().uuid().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Create a draft template with version 1
 */
export const createPlatformContactTemplateBodyKeyMin = 2;
export const createPlatformContactTemplateBodyKeyMax = 80;

export const createPlatformContactTemplateBodyInternalNameMin = 2;
export const createPlatformContactTemplateBodyInternalNameMax = 120;

export const createPlatformContactTemplateBodyCategoryMax = 40;

export const createPlatformContactTemplateBodyLanguageDefault = `en`;
export const createPlatformContactTemplateBodyLanguageMax = 8;

export const createPlatformContactTemplateBodySubjectMax = 200;

export const createPlatformContactTemplateBodyBodyMax = 20000;

export const CreatePlatformContactTemplateBody = zod.object({
  key: zod
    .string()
    .min(createPlatformContactTemplateBodyKeyMin)
    .max(createPlatformContactTemplateBodyKeyMax),
  internalName: zod
    .string()
    .min(createPlatformContactTemplateBodyInternalNameMin)
    .max(createPlatformContactTemplateBodyInternalNameMax),
  category: zod.string().max(createPlatformContactTemplateBodyCategoryMax),
  language: zod
    .string()
    .max(createPlatformContactTemplateBodyLanguageMax)
    .default(createPlatformContactTemplateBodyLanguageDefault),
  subject: zod.string().min(1).max(createPlatformContactTemplateBodySubjectMax),
  body: zod.string().min(1).max(createPlatformContactTemplateBodyBodyMax),
});

/**
 * @summary Publish a template
 */
export const PublishPlatformContactTemplateParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const PublishPlatformContactTemplateResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary Append a new template version
 */
export const CreatePlatformContactTemplateVersionParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const createPlatformContactTemplateVersionBodyLanguageDefault = `en`;
export const createPlatformContactTemplateVersionBodyLanguageMax = 8;

export const createPlatformContactTemplateVersionBodyChangeSummaryMax = 200;

export const CreatePlatformContactTemplateVersionBody = zod.object({
  language: zod
    .string()
    .max(createPlatformContactTemplateVersionBodyLanguageMax)
    .default(createPlatformContactTemplateVersionBodyLanguageDefault),
  subject: zod.string().min(1),
  body: zod.string().min(1),
  changeSummary: zod
    .string()
    .max(createPlatformContactTemplateVersionBodyChangeSummaryMax)
    .optional(),
});

/**
 * @summary Read taxonomy, models, workflows, routing, SLA, meetings, macros, tags
 */
export const GetPlatformContactConfigResponse = zod.object({
  taxonomy: zod.array(
    zod.object({
      id: zod.string(),
      kind: zod.string(),
      key: zod.string(),
      parentKey: zod.string(),
      label: zod.string(),
      description: zod.string().nullish(),
      sortOrder: zod.number(),
      active: zod.boolean(),
      metadata: zod.record(zod.string(), zod.unknown()).optional(),
    }),
  ),
  models: zod.array(
    zod.object({
      id: zod.string().uuid(),
      key: zod.string(),
      name: zod.string(),
      version: zod.number(),
      status: zod.string(),
      thresholds: zod.record(zod.string(), zod.unknown()),
      rules: zod.array(zod.record(zod.string(), zod.unknown())),
      publishedAt: zod.coerce.date().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  workflows: zod.array(
    zod.object({
      id: zod.string().uuid(),
      key: zod.string(),
      name: zod.string(),
      status: zod.string(),
      version: zod.number(),
      trigger: zod.string(),
      conditions: zod.array(zod.record(zod.string(), zod.unknown())),
      actions: zod.array(zod.record(zod.string(), zod.unknown())),
      createdAt: zod.coerce.date(),
      updatedAt: zod.coerce.date(),
    }),
  ),
  routing: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      priority: zod.number(),
      status: zod.string(),
      conditions: zod.array(zod.record(zod.string(), zod.unknown())),
      strategy: zod.string(),
      teamId: zod.string().uuid().nullish(),
      staffId: zod.string().uuid().nullish(),
      reasonTemplate: zod.string().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  sla: zod.array(
    zod.object({
      id: zod.string().uuid(),
      key: zod.string(),
      name: zod.string(),
      version: zod.number(),
      status: zod.string(),
      firstResponseMinutes: zod.number(),
      nextResponseMinutes: zod.number().nullish(),
      resolutionMinutes: zod.number().nullish(),
      conditions: zod.array(zod.record(zod.string(), zod.unknown())),
      createdAt: zod.coerce.date(),
    }),
  ),
  meetings: zod.array(
    zod.object({
      id: zod.string().uuid(),
      key: zod.string(),
      name: zod.string(),
      durationMinutes: zod.number(),
      timezone: zod.string(),
      bookingUrl: zod.string(),
      teamId: zod.string().uuid().nullish(),
      calendarSource: zod.string(),
      status: zod.string(),
    }),
  ),
  macros: zod.array(
    zod.object({
      id: zod.string().uuid(),
      key: zod.string(),
      name: zod.string(),
      description: zod.string().nullish(),
      actions: zod.array(zod.record(zod.string(), zod.unknown())),
      status: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
  tags: zod.array(
    zod.object({
      id: zod.string().uuid(),
      slug: zod.string(),
      label: zod.string(),
      color: zod.string().nullish(),
    }),
  ),
});

/**
 * @summary Update taxonomy label, sort order, and active flag
 */
export const UpdatePlatformTaxonomyItemParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const updatePlatformTaxonomyItemBodyLabelMax = 200;

export const UpdatePlatformTaxonomyItemBody = zod.object({
  label: zod
    .string()
    .min(1)
    .max(updatePlatformTaxonomyItemBodyLabelMax)
    .optional(),
  sortOrder: zod.number().optional(),
  active: zod.boolean().optional(),
});

export const UpdatePlatformTaxonomyItemResponse = zod.object({
  id: zod.string(),
  kind: zod.string(),
  key: zod.string(),
  parentKey: zod.string(),
  label: zod.string(),
  description: zod.string().nullish(),
  sortOrder: zod.number(),
  active: zod.boolean(),
  metadata: zod.record(zod.string(), zod.unknown()).optional(),
});

/**
 * @summary Archive the current model and publish the next version
 */
export const UpdatePlatformQualificationModelParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const UpdatePlatformQualificationModelBody = zod.object({
  thresholds: zod.record(zod.string(), zod.number()),
  rules: zod.array(zod.record(zod.string(), zod.unknown())),
  name: zod.string().optional(),
});

export const UpdatePlatformQualificationModelResponse = zod.object({
  id: zod.string().uuid(),
  key: zod.string(),
  name: zod.string(),
  version: zod.number(),
  status: zod.string(),
  thresholds: zod.record(zod.string(), zod.unknown()),
  rules: zod.array(zod.record(zod.string(), zod.unknown())),
  publishedAt: zod.coerce.date().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update a workflow (increments version)
 */
export const UpdatePlatformWorkflowParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const UpdatePlatformWorkflowBody = zod.object({
  name: zod.string().optional(),
  status: zod.enum(["active", "disabled"]).optional(),
  conditions: zod.array(zod.record(zod.string(), zod.unknown())).optional(),
  actions: zod.array(zod.record(zod.string(), zod.unknown())).optional(),
});

export const UpdatePlatformWorkflowResponse = zod.object({
  id: zod.string().uuid(),
  key: zod.string(),
  name: zod.string(),
  status: zod.string(),
  version: zod.number(),
  trigger: zod.string(),
  conditions: zod.array(zod.record(zod.string(), zod.unknown())),
  actions: zod.array(zod.record(zod.string(), zod.unknown())),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Update a routing rule
 */
export const UpdatePlatformRoutingRuleParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const UpdatePlatformRoutingRuleBody = zod.object({
  name: zod.string().optional(),
  priority: zod.number().optional(),
  status: zod.enum(["active", "disabled"]).optional(),
  conditions: zod.array(zod.record(zod.string(), zod.unknown())).optional(),
  strategy: zod.string().optional(),
  teamId: zod.string().uuid().nullish(),
  staffId: zod.string().uuid().nullish(),
  reasonTemplate: zod.string().optional(),
});

export const UpdatePlatformRoutingRuleResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  priority: zod.number(),
  status: zod.string(),
  conditions: zod.array(zod.record(zod.string(), zod.unknown())),
  strategy: zod.string(),
  teamId: zod.string().uuid().nullish(),
  staffId: zod.string().uuid().nullish(),
  reasonTemplate: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update an SLA policy (increments version)
 */
export const UpdatePlatformSlaPolicyParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const UpdatePlatformSlaPolicyBody = zod.object({
  name: zod.string().optional(),
  firstResponseMinutes: zod.number().optional(),
  nextResponseMinutes: zod.number().nullish(),
  resolutionMinutes: zod.number().nullish(),
  conditions: zod.array(zod.record(zod.string(), zod.unknown())).optional(),
  status: zod.enum(["active", "disabled"]).optional(),
});

export const UpdatePlatformSlaPolicyResponse = zod.object({
  id: zod.string().uuid(),
  key: zod.string(),
  name: zod.string(),
  version: zod.number(),
  status: zod.string(),
  firstResponseMinutes: zod.number(),
  nextResponseMinutes: zod.number().nullish(),
  resolutionMinutes: zod.number().nullish(),
  conditions: zod.array(zod.record(zod.string(), zod.unknown())),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update a meeting type (external booking URL)
 */
export const UpdatePlatformMeetingTypeParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const UpdatePlatformMeetingTypeBody = zod.object({
  name: zod.string().optional(),
  bookingUrl: zod.string().url().optional(),
  durationMinutes: zod.number().optional(),
  timezone: zod.string().optional(),
  status: zod.enum(["active", "disabled"]).optional(),
});

export const UpdatePlatformMeetingTypeResponse = zod.object({
  id: zod.string().uuid(),
  key: zod.string(),
  name: zod.string(),
  durationMinutes: zod.number(),
  timezone: zod.string(),
  bookingUrl: zod.string(),
  teamId: zod.string().uuid().nullish(),
  calendarSource: zod.string(),
  status: zod.string(),
});

/**
 * @summary Create a governed draft for a macro (does not mutate live config)
 */
export const UpdatePlatformMacroParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const updatePlatformMacroBodyRationaleMax = 500;

export const UpdatePlatformMacroBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().nullish(),
  status: zod.enum(["active", "disabled"]).optional(),
  actions: zod.array(zod.record(zod.string(), zod.unknown())).optional(),
  rationale: zod.string().max(updatePlatformMacroBodyRationaleMax).optional(),
});

/**
 * @summary Create a governed draft for a tag (does not mutate live config)
 */
export const UpdatePlatformTagParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const updatePlatformTagBodyRationaleMax = 500;

export const UpdatePlatformTagBody = zod.object({
  label: zod.string().optional(),
  color: zod.string().nullish(),
  rationale: zod.string().max(updatePlatformTagBodyRationaleMax).optional(),
});

/**
 * @summary Create a governed draft for notification policy
 */
export const updatePlatformNotificationPolicyBodyRationaleMax = 500;

export const UpdatePlatformNotificationPolicyBody = zod.object({
  channels: zod.array(zod.string()).optional(),
  slaBreach: zod.boolean().optional(),
  assignment: zod.boolean().optional(),
  rationale: zod
    .string()
    .max(updatePlatformNotificationPolicyBodyRationaleMax)
    .optional(),
});

/**
 * @summary Create a governed draft for business calendar
 */
export const updatePlatformBusinessCalendarBodyTimeZoneMax = 80;

export const updatePlatformBusinessCalendarBodyWeekdaysItemMin = 0;
export const updatePlatformBusinessCalendarBodyWeekdaysItemMax = 6;

export const updatePlatformBusinessCalendarBodyOpenHourDefault = 9;
export const updatePlatformBusinessCalendarBodyOpenHourMin = 0;
export const updatePlatformBusinessCalendarBodyOpenHourMax = 23;

export const updatePlatformBusinessCalendarBodyCloseHourDefault = 17;
export const updatePlatformBusinessCalendarBodyCloseHourMax = 24;

export const updatePlatformBusinessCalendarBodyRationaleMax = 500;

export const UpdatePlatformBusinessCalendarBody = zod.object({
  timeZone: zod.string().max(updatePlatformBusinessCalendarBodyTimeZoneMax),
  weekdays: zod
    .array(
      zod
        .number()
        .min(updatePlatformBusinessCalendarBodyWeekdaysItemMin)
        .max(updatePlatformBusinessCalendarBodyWeekdaysItemMax),
    )
    .min(1),
  openHour: zod
    .number()
    .min(updatePlatformBusinessCalendarBodyOpenHourMin)
    .max(updatePlatformBusinessCalendarBodyOpenHourMax)
    .default(updatePlatformBusinessCalendarBodyOpenHourDefault),
  closeHour: zod
    .number()
    .min(1)
    .max(updatePlatformBusinessCalendarBodyCloseHourMax)
    .default(updatePlatformBusinessCalendarBodyCloseHourDefault),
  holidays: zod.array(zod.string()).optional(),
  rationale: zod
    .string()
    .max(updatePlatformBusinessCalendarBodyRationaleMax)
    .optional(),
});

/**
 * @summary Create a governed draft for retention policy
 */
export const updatePlatformRetentionPolicyBodyRetainDaysMax = 3650;

export const updatePlatformRetentionPolicyBodyAnonymizeMessagesDefault = true;
export const updatePlatformRetentionPolicyBodyRationaleMax = 500;

export const UpdatePlatformRetentionPolicyBody = zod.object({
  retainDays: zod
    .number()
    .min(1)
    .max(updatePlatformRetentionPolicyBodyRetainDaysMax),
  anonymizeMessages: zod
    .boolean()
    .default(updatePlatformRetentionPolicyBodyAnonymizeMessagesDefault),
  rationale: zod
    .string()
    .max(updatePlatformRetentionPolicyBodyRationaleMax)
    .optional(),
});

/**
 * @summary Create a governed draft for spam/bot policy
 */
export const updatePlatformSpamBotPolicyBodyBlockScoreMin = 0;
export const updatePlatformSpamBotPolicyBodyBlockScoreMax = 100;

export const updatePlatformSpamBotPolicyBodyHoneypotRejectDefault = true;
export const updatePlatformSpamBotPolicyBodyRationaleMax = 500;

export const UpdatePlatformSpamBotPolicyBody = zod.object({
  blockScore: zod
    .number()
    .min(updatePlatformSpamBotPolicyBodyBlockScoreMin)
    .max(updatePlatformSpamBotPolicyBodyBlockScoreMax),
  honeypotReject: zod
    .boolean()
    .default(updatePlatformSpamBotPolicyBodyHoneypotRejectDefault),
  rationale: zod
    .string()
    .max(updatePlatformSpamBotPolicyBodyRationaleMax)
    .optional(),
});

/**
 * @summary Pause open SLA clocks for an inquiry
 */
export const PausePlatformInquirySlaParams = zod.object({
  id: zod.coerce.string().uuid(),
});

/**
 * @summary Resume paused SLA clocks for an inquiry
 */
export const ResumePlatformInquirySlaParams = zod.object({
  id: zod.coerce.string().uuid(),
});

/**
 * @summary Merge a duplicate contact into a surviving contact
 */
export const MergePlatformContactsBody = zod.object({
  winnerId: zod.string().uuid(),
  loserId: zod.string().uuid(),
});

/**
 * @summary Find duplicate contacts by email or phone
 */
export const ListPlatformContactDuplicatesQueryParams = zod.object({
  email: zod.coerce.string().email().optional(),
  phone: zod.coerce.string().optional(),
});

export const ListPlatformContactDuplicatesResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid().optional(),
      email: zod.string().optional(),
      firstName: zod.string().optional(),
      lastName: zod.string().optional(),
      phoneE164: zod.string().nullish(),
      companyId: zod.string().uuid().nullish(),
      updatedAt: zod.coerce.date().optional(),
    }),
  ),
  matchOn: zod.object({
    email: zod.string().nullish(),
    phone: zod.string().nullish(),
  }),
});

/**
 * @summary Search dead-letter jobs
 */
export const ListPlatformDeadLetterJobsQueryParams = zod.object({
  q: zod.coerce.string().optional(),
  type: zod.coerce.string().optional(),
});

export const ListPlatformDeadLetterJobsResponse = zod.object({
  items: zod.array(zod.record(zod.string(), zod.unknown())),
});

/**
 * @summary Authorized dead-letter replay
 */
export const ReplayPlatformDeadLetterJobParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const replayPlatformDeadLetterJobBodyReasonMin = 5;

export const ReplayPlatformDeadLetterJobBody = zod.object({
  reason: zod.string().min(replayPlatformDeadLetterJobBodyReasonMin),
});

export const ReplayPlatformDeadLetterJobResponse = zod.object({
  replayed: zod.boolean(),
  id: zod.string().uuid(),
});

/**
 * @summary Inspect job effects
 */
export const listPlatformJobEffectsQueryLimitDefault = 50;
export const listPlatformJobEffectsQueryLimitMax = 200;

export const ListPlatformJobEffectsQueryParams = zod.object({
  status: zod.coerce.string().optional(),
  limit: zod.coerce
    .number()
    .min(1)
    .max(listPlatformJobEffectsQueryLimitMax)
    .default(listPlatformJobEffectsQueryLimitDefault),
});

export const ListPlatformJobEffectsResponse = zod.object({
  effects: zod.array(zod.record(zod.string(), zod.unknown())),
  metrics: zod.record(zod.string(), zod.unknown()).optional(),
});

/**
 * @summary Load one job effect by idempotency key
 */
export const GetPlatformJobEffectParams = zod.object({
  key: zod.coerce.string(),
});

export const GetPlatformJobEffectResponse = zod.object({
  effect: zod.record(zod.string(), zod.unknown()),
});

/**
 * @summary Reconcile an uncertain outbound email effect
 */
export const ReconcilePlatformJobEffectParams = zod.object({
  key: zod.coerce.string(),
});

export const ReconcilePlatformJobEffectResponse = zod.object({
  key: zod.string(),
  outcome: zod.string(),
});

/**
 * @summary Authorized terminal/uncertain effect replay
 */
export const ReplayPlatformJobEffectParams = zod.object({
  key: zod.coerce.string(),
});

export const ReplayPlatformJobEffectBody = zod.object({
  reason: zod.string(),
});

/**
 * @summary DSAR intake
 */
export const CreatePlatformDsarRequestBody = zod.object({
  contactId: zod.string().uuid(),
  requestType: zod.enum([
    "access",
    "export",
    "correction",
    "deletion",
    "objection",
  ]),
  notes: zod.string().optional(),
});

export const TransitionPlatformDsarRequestParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const TransitionPlatformDsarRequestBody = zod.object({
  status: zod.string(),
  identityVerified: zod.boolean().optional(),
  legalExceptionReason: zod.string().optional(),
  rejectionReason: zod.string().optional(),
});

export const ExportPlatformDsarRequestParams = zod.object({
  id: zod.coerce.string().uuid(),
});

/**
 * @summary Apply a DSAR correction patch to the subject contact
 */
export const CorrectPlatformDsarRequestParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const correctPlatformDsarRequestBodyFirstNameMax = 120;

export const correctPlatformDsarRequestBodyLastNameMax = 120;

export const correctPlatformDsarRequestBodyJobTitleMax = 200;

export const correctPlatformDsarRequestBodyEmailMax = 320;

export const correctPlatformDsarRequestBodyPhoneMax = 40;

export const CorrectPlatformDsarRequestBody = zod.object({
  firstName: zod
    .string()
    .max(correctPlatformDsarRequestBodyFirstNameMax)
    .optional(),
  lastName: zod
    .string()
    .max(correctPlatformDsarRequestBodyLastNameMax)
    .optional(),
  jobTitle: zod
    .string()
    .max(correctPlatformDsarRequestBodyJobTitleMax)
    .optional(),
  email: zod
    .string()
    .email()
    .max(correctPlatformDsarRequestBodyEmailMax)
    .optional(),
  phone: zod.string().max(correctPlatformDsarRequestBodyPhoneMax).optional(),
});

export const CorrectPlatformDsarRequestResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary Complete a DSAR deletion / anonymization
 */
export const DeletePlatformDsarRequestParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const DeletePlatformDsarRequestResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary Complete a DSAR objection
 */
export const ObjectPlatformDsarRequestParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ObjectPlatformDsarRequestBody = zod.object({
  notes: zod.string().optional(),
});

export const ObjectPlatformDsarRequestResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary List attachment metadata
 */
export const ListPlatformAttachmentsQueryParams = zod.object({
  status: zod.coerce
    .string()
    .optional()
    .describe("Filter by malwareStatus (e.g. quarantined, clean, pending)"),
});

export const ListPlatformAttachmentsResponse = zod.object({
  attachments: zod.array(zod.record(zod.string(), zod.unknown())),
});

/**
 * @summary Store attachment metadata and bytes via test/object adapter
 */
export const CreatePlatformAttachmentBody = zod.object({
  filename: zod.string(),
  mimeType: zod.string(),
  contentBase64: zod.string(),
  inquiryId: zod.string().uuid().optional(),
  contactId: zod.string().uuid().optional(),
  visibility: zod.enum(["internal", "customer"]).optional(),
});

/**
 * @summary Manually release a quarantined attachment
 */
export const ReleasePlatformAttachmentQuarantineParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ReleasePlatformAttachmentQuarantineBody = zod.object({
  reason: zod.string().optional(),
});

export const ReleasePlatformAttachmentQuarantineResponse = zod.object({
  attachment: zod.record(zod.string(), zod.unknown()),
});

/**
 * @summary Convert inquiry to opportunity
 */
export const ConvertPlatformInquiryOpportunityParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ConvertPlatformInquiryOpportunityBody = zod.object({
  idempotencyKey: zod.string(),
  amountCents: zod.number().optional(),
  currency: zod.string().optional(),
});

/**
 * @summary Latest notifications for the current staff (max 40)
 */
export const ListPlatformContactNotificationsResponseItem = zod.object({
  id: zod.string().uuid(),
  staffId: zod.string().uuid(),
  inquiryId: zod.string().uuid().nullish(),
  type: zod.string(),
  title: zod.string(),
  body: zod.string().nullish(),
  readAt: zod.coerce.date().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListPlatformContactNotificationsResponse = zod.array(
  ListPlatformContactNotificationsResponseItem,
);

/**
 * @summary List saved inbox views for the current staff
 */
export const ListPlatformSavedViewsResponseItem = zod.object({
  id: zod.string().uuid(),
  staffId: zod.string().uuid(),
  name: zod.string(),
  filters: zod.record(zod.string(), zod.unknown()),
  columns: zod.array(zod.string()).nullish(),
  sort: zod.record(zod.string(), zod.unknown()).optional(),
  createdAt: zod.coerce.date(),
});
export const ListPlatformSavedViewsResponse = zod.array(
  ListPlatformSavedViewsResponseItem,
);

/**
 * @summary Create a saved inbox view
 */
export const createPlatformSavedViewBodyNameMax = 80;

export const CreatePlatformSavedViewBody = zod.object({
  name: zod.string().min(1).max(createPlatformSavedViewBodyNameMax),
  filters: zod.record(zod.string(), zod.unknown()),
});

/**
 * Returns a saved view owned by the authenticated staff member.
 * @summary Get one saved view
 */
export const GetPlatformSavedViewParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const GetPlatformSavedViewResponse = zod.object({
  id: zod.string().uuid(),
  staffId: zod.string().uuid(),
  name: zod.string(),
  filters: zod.record(zod.string(), zod.unknown()),
  columns: zod.array(zod.string()).nullish(),
  sort: zod.record(zod.string(), zod.unknown()).optional(),
  createdAt: zod.coerce.date(),
});

/**
 * Updates name, filters, columns, sort, default flag, or ownership transfer with optional optimistic concurrency.
 * @summary Update a saved view
 */
export const UpdatePlatformSavedViewParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const updatePlatformSavedViewBodyNameMax = 80;

export const UpdatePlatformSavedViewBody = zod.object({
  name: zod.string().min(1).max(updatePlatformSavedViewBodyNameMax).optional(),
  filters: zod.record(zod.string(), zod.unknown()).optional(),
  columns: zod.array(zod.string()).optional(),
  sort: zod.record(zod.string(), zod.unknown()).optional(),
});

export const UpdatePlatformSavedViewResponse = zod.object({
  id: zod.string().uuid(),
  staffId: zod.string().uuid(),
  name: zod.string(),
  filters: zod.record(zod.string(), zod.unknown()),
  columns: zod.array(zod.string()).nullish(),
  sort: zod.record(zod.string(), zod.unknown()).optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a saved view
 */
export const DeletePlatformSavedViewParams = zod.object({
  id: zod.coerce.string().uuid(),
});

/**
 * @summary Aggregate inquiry, country, event, and SLA counts
 */
export const getPlatformContactAnalyticsQueryTimeZoneDefault = `UTC`;

export const GetPlatformContactAnalyticsQueryParams = zod.object({
  from: zod.date().optional(),
  to: zod.date().optional(),
  timeZone: zod.coerce
    .string()
    .default(getPlatformContactAnalyticsQueryTimeZoneDefault),
  format: zod.enum(["json", "csv"]).optional(),
});

export const GetPlatformContactAnalyticsResponse = zod.object({
  totals: zod.object({
    total: zod.number(),
    qualified: zod.number(),
    open: zod.number(),
  }),
  byCountry: zod.array(
    zod.object({
      country: zod.string(),
      count: zod.number(),
    }),
  ),
  events: zod.array(
    zod.object({
      event: zod.string(),
      count: zod.number(),
    }),
  ),
  sla: zod.object({
    breached: zod.number(),
    onTrack: zod.number(),
    atRisk: zod.number(),
  }),
});

/**
 * @summary Bulk-assign inquiries after confirmation
 */
export const BulkAssignPlatformInquiriesBody = zod.object({
  ids: zod.array(zod.string().uuid()),
  staffId: zod.string().uuid(),
  confirm: zod.boolean(),
});

export const BulkAssignPlatformInquiriesResponse = zod.object({
  updated: zod.number().optional(),
  succeeded: zod.array(zod.string().uuid()).optional(),
  failed: zod
    .array(
      zod.object({
        id: zod.string().uuid().optional(),
        reason: zod.string().optional(),
      }),
    )
    .optional(),
});

/**
 * @summary Bulk-update inquiry status after confirmation
 */
export const BulkStatusPlatformInquiriesBody = zod.object({
  ids: zod.array(zod.string().uuid()),
  status: zod.string(),
  confirm: zod.boolean(),
});

export const BulkStatusPlatformInquiriesResponse = zod.object({
  updated: zod.number().optional(),
  succeeded: zod.array(zod.string().uuid()).optional(),
  failed: zod
    .array(
      zod.object({
        id: zod.string().uuid().optional(),
        reason: zod.string().optional(),
      }),
    )
    .optional(),
});

/**
 * @summary List configuration change requests
 */
export const ListPlatformConfigChangesQueryParams = zod.object({
  entityType: zod.coerce.string().optional(),
});

export const ListPlatformConfigChangesResponse = zod.object({
  items: zod.array(zod.record(zod.string(), zod.unknown())),
});

/**
 * @summary Create a draft configuration change
 */
export const createPlatformConfigChangeBodyEntityTypeMin = 2;
export const createPlatformConfigChangeBodyEntityTypeMax = 80;

export const createPlatformConfigChangeBodyEntityIdMax = 80;

export const createPlatformConfigChangeBodyRationaleMax = 500;

export const CreatePlatformConfigChangeBody = zod.object({
  entityType: zod
    .string()
    .min(createPlatformConfigChangeBodyEntityTypeMin)
    .max(createPlatformConfigChangeBodyEntityTypeMax),
  entityId: zod.string().min(1).max(createPlatformConfigChangeBodyEntityIdMax),
  afterValue: zod.record(zod.string(), zod.unknown()),
  beforeValue: zod.record(zod.string(), zod.unknown()).nullish(),
  effectiveAt: zod.coerce.date().optional(),
  rationale: zod
    .string()
    .max(createPlatformConfigChangeBodyRationaleMax)
    .optional(),
});

/**
 * @summary Advance a configuration change (review, approve, publish, rollback)
 */
export const ActPlatformConfigChangeParams = zod.object({
  id: zod.coerce.string().uuid(),
  action: zod.enum([
    "submit_review",
    "approve",
    "reject",
    "publish",
    "rollback",
    "revise",
  ]),
});

export const actPlatformConfigChangeBodyRationaleMax = 500;

export const actPlatformConfigChangeBodyEmergencyReasonMax = 500;

export const ActPlatformConfigChangeBody = zod.object({
  expectedLockVersion: zod.number(),
  expectedPublishedVersion: zod.number().optional(),
  rationale: zod
    .string()
    .max(actPlatformConfigChangeBodyRationaleMax)
    .optional(),
  emergencyBypass: zod.boolean().optional(),
  emergencyReason: zod
    .string()
    .max(actPlatformConfigChangeBodyEmergencyReasonMax)
    .optional(),
});

/**
 * @summary Authorize replay of a terminal failed inbound webhook receipt
 */
export const ReplayPlatformWebhookReceiptParams = zod.object({
  eventId: zod.coerce.string(),
});

/**
 * @summary Synchronous DSAR package for a contact
 */
export const PostPlatformGovernanceDsarExportBody = zod.object({
  contactId: zod.string().uuid(),
});

/**
 * @summary Place a legal hold on a contact or inquiry
 */
export const PostPlatformLegalHoldBody = zod.object({
  contactId: zod.string().uuid().optional(),
  inquiryId: zod.string().uuid().optional(),
  reason: zod.string(),
});

/**
 * @summary Release an active legal hold
 */
export const ReleasePlatformLegalHoldParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ReleasePlatformLegalHoldResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary Enforce inquiry retention / anonymization policy
 */
export const RunPlatformRetentionResponse = zod.object({
  processed: zod.number(),
});

/**
 * @summary Invite a staff member by email (allowlist alternative)
 */
export const InvitePlatformStaffBody = zod.object({
  email: zod.string().email(),
  role: zod.enum(["owner", "admin", "sales", "operator", "analyst"]).optional(),
});

/**
 * Lists immutable CRM audit events. Optional `inquiryId` filters to one inquiry.
Per-inquiry detail also embeds the newest 80 events on
`GET /platform/contact/inquiries/{id}`.

 * @summary Paginated audit event list
 */
export const listPlatformContactAuditQueryLimitDefault = 50;
export const listPlatformContactAuditQueryLimitMax = 100;

export const ListPlatformContactAuditQueryParams = zod.object({
  limit: zod.coerce
    .number()
    .min(1)
    .max(listPlatformContactAuditQueryLimitMax)
    .default(listPlatformContactAuditQueryLimitDefault)
    .describe("Inbox default 50, capped at 100."),
  inquiryId: zod.coerce.string().uuid().optional(),
});

export const ListPlatformContactAuditResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      actorType: zod.string(),
      actorId: zod.string().nullish(),
      action: zod.string(),
      entityType: zod.string(),
      entityId: zod.string(),
      inquiryId: zod.string().uuid().nullish(),
      contactId: zod.string().uuid().nullish(),
      beforeValue: zod.record(zod.string(), zod.unknown()).optional(),
      afterValue: zod.record(zod.string(), zod.unknown()).optional(),
      workflowId: zod.string().uuid().nullish(),
      correlationId: zod.string().nullish(),
      createdAt: zod.coerce.date(),
    }),
  ),
  total: zod.number(),
  limit: zod.number(),
  offset: zod.number(),
});

/**
 * Enqueues a durable DSAR export job. The 202 body is status-only (no package PII).
Download uses the owned export artifact URL after completion. Not a statutory-compliance certification.

 * @summary Subject-access (DSAR) export for a contact
 */
export const ExportPlatformContactDsarParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ExportPlatformContactDsarHeader = zod.object({
  "Idempotency-Key": zod
    .string()
    .uuid()
    .optional()
    .describe(
      "Recommended client header for retry-safe writes. Public submit currently\nrequires the same UUID in the JSON body field `idempotencyKey`; the\nserver does not read this header yet. Planned DSAR export should honor it.\n",
    ),
});

/**
 * @summary Fetch a DSAR export job status (no package PII)
 */
export const GetPlatformContactDsarExportParams = zod.object({
  exportId: zod.coerce.string().uuid(),
});

export const GetPlatformContactDsarExportResponse = zod.object({
  exportId: zod.string().uuid(),
  status: zod.enum(["pending", "running", "ready", "failed", "cancelled"]),
  contactId: zod.string().uuid(),
  createdAt: zod.coerce.date(),
  completedAt: zod.coerce.date().nullish(),
  expiresAt: zod.coerce.date().nullish(),
  downloadUrl: zod.string().nullish(),
  error: zod.string().nullish(),
});

/**
 * @summary List live presence for an entity
 */
export const GetPlatformContactPresenceQueryParams = zod.object({
  entityType: zod.enum(["inquiry", "marketing_version", "config_change"]),
  entityId: zod.coerce.string().uuid(),
});

export const GetPlatformContactPresenceResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary Heartbeat staff presence on an entity
 */
export const heartbeatPlatformContactPresenceBodyIntentMax = 40;

export const HeartbeatPlatformContactPresenceBody = zod.object({
  entityType: zod.enum(["inquiry", "marketing_version", "config_change"]),
  entityId: zod.string().uuid(),
  intent: zod
    .string()
    .max(heartbeatPlatformContactPresenceBodyIntentMax)
    .optional(),
});

export const HeartbeatPlatformContactPresenceResponse = zod.object({
  presence: zod.record(zod.string(), zod.unknown()),
});

/**
 * @summary Acquire an exclusive record lock
 */
export const acquirePlatformRecordLockBodyIntentMax = 40;

export const AcquirePlatformRecordLockBody = zod.object({
  entityType: zod.enum(["inquiry", "marketing_version", "config_change"]),
  entityId: zod.string().uuid(),
  intent: zod.string().max(acquirePlatformRecordLockBodyIntentMax).optional(),
});

/**
 * @summary Heartbeat a held record lock
 */
export const HeartbeatPlatformRecordLockParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const HeartbeatPlatformRecordLockResponse = zod.object({
  lock: zod.object({
    id: zod.string().uuid(),
    entityType: zod.enum(["inquiry", "marketing_version", "config_change"]),
    entityId: zod.string().uuid(),
    holderStaffId: zod.string().uuid().optional(),
  }),
});

/**
 * @summary Release a held record lock
 */
export const ReleasePlatformRecordLockParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ReleasePlatformRecordLockResponse = zod.record(
  zod.string(),
  zod.unknown(),
);

/**
 * @summary Force-take a record lock with reason
 */
export const OverridePlatformRecordLockParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const overridePlatformRecordLockBodyReasonMin = 5;
export const overridePlatformRecordLockBodyReasonMax = 500;

export const OverridePlatformRecordLockBody = zod.object({
  reason: zod
    .string()
    .min(overridePlatformRecordLockBodyReasonMin)
    .max(overridePlatformRecordLockBodyReasonMax),
});

export const OverridePlatformRecordLockResponse = zod.object({
  lock: zod.object({
    id: zod.string().uuid(),
    entityType: zod.enum(["inquiry", "marketing_version", "config_change"]),
    entityId: zod.string().uuid(),
    holderStaffId: zod.string().uuid().optional(),
  }),
});

/**
 * @summary Enqueue an async inquiry CSV export
 */
export const createPlatformContactExportBodyColumnsItemMax = 64;

export const createPlatformContactExportBodyColumnsMax = 40;

export const CreatePlatformContactExportBody = zod.object({
  filters: zod.record(zod.string(), zod.unknown()).optional(),
  columns: zod
    .array(zod.string().max(createPlatformContactExportBodyColumnsItemMax))
    .max(createPlatformContactExportBodyColumnsMax)
    .optional(),
});

/**
 * @summary List export jobs for the caller
 */
export const listPlatformContactExportsQueryLimitDefault = 50;
export const listPlatformContactExportsQueryLimitMax = 200;

export const ListPlatformContactExportsQueryParams = zod.object({
  limit: zod.coerce
    .number()
    .min(1)
    .max(listPlatformContactExportsQueryLimitMax)
    .default(listPlatformContactExportsQueryLimitDefault),
});

export const ListPlatformContactExportsResponse = zod.object({
  jobs: zod.array(
    zod.object({
      id: zod.string().uuid(),
      status: zod.string().optional(),
    }),
  ),
});

/**
 * @summary Get one export job
 */
export const GetPlatformContactExportParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const GetPlatformContactExportResponse = zod.object({
  job: zod.object({
    id: zod.string().uuid(),
    status: zod.string().optional(),
  }),
});

/**
 * @summary Cancel a pending/running export job
 */
export const CancelPlatformContactExportParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const CancelPlatformContactExportResponse = zod.object({
  job: zod.object({
    id: zod.string().uuid(),
    status: zod.string().optional(),
  }),
});

/**
 * @summary Download a completed export CSV
 */
export const DownloadPlatformContactExportParams = zod.object({
  id: zod.coerce.string().uuid(),
});

/**
 * @summary List marketing documents
 */
export const ListPlatformMarketingDocumentsResponse = zod.object({
  documents: zod.array(
    zod.object({
      id: zod.string().uuid(),
      slug: zod.string(),
      contentType: zod.string(),
      updatedAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Create a marketing document draft version
 */

export const createPlatformMarketingDocumentDraftBodyLocaleDefault = `en`;

export const CreatePlatformMarketingDocumentDraftBody = zod.object({
  slug: zod.string().min(1),
  locale: zod
    .string()
    .default(createPlatformMarketingDocumentDraftBodyLocaleDefault),
  title: zod.string().min(1),
  summary: zod.string().optional(),
  body: zod.record(zod.string(), zod.unknown()).optional(),
  seoTitle: zod.string().optional(),
  seoDescription: zod.string().optional(),
  robots: zod.string().optional(),
});

/**
 * @summary List versions for a marketing document
 */
export const ListPlatformMarketingDocumentVersionsParams = zod.object({
  slug: zod.coerce.string(),
});

export const ListPlatformMarketingDocumentVersionsResponse = zod.object({
  document: zod.object({
    id: zod.string().uuid(),
    slug: zod.string(),
    contentType: zod.string(),
    updatedAt: zod.coerce.date(),
  }),
  versions: zod.array(
    zod.object({
      id: zod.string().uuid(),
      documentId: zod.string().uuid(),
      locale: zod.string(),
      version: zod.number(),
      status: zod.enum([
        "draft",
        "in_review",
        "changes_requested",
        "approved",
        "scheduled",
        "published",
        "superseded",
        "archived",
      ]),
      title: zod.string(),
      summary: zod.string().nullish(),
      body: zod.record(zod.string(), zod.unknown()),
      seoTitle: zod.string().nullish(),
      seoDescription: zod.string().nullish(),
      lockVersion: zod.number(),
    }),
  ),
});

/**
 * @summary Immutable marketing audit trail for a document
 */
export const ListPlatformMarketingDocumentAuditParams = zod.object({
  slug: zod.coerce.string(),
});

export const ListPlatformMarketingDocumentAuditResponse = zod.object({
  document: zod.object({
    id: zod.string().uuid(),
    slug: zod.string(),
    contentType: zod.string(),
    updatedAt: zod.coerce.date(),
  }),
  audit: zod.array(
    zod.object({
      id: zod.string().uuid(),
      action: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Get a marketing version
 */
export const GetPlatformMarketingVersionParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const GetPlatformMarketingVersionResponse = zod.object({
  version: zod.object({
    id: zod.string().uuid(),
    documentId: zod.string().uuid(),
    locale: zod.string(),
    version: zod.number(),
    status: zod.enum([
      "draft",
      "in_review",
      "changes_requested",
      "approved",
      "scheduled",
      "published",
      "superseded",
      "archived",
    ]),
    title: zod.string(),
    summary: zod.string().nullish(),
    body: zod.record(zod.string(), zod.unknown()),
    seoTitle: zod.string().nullish(),
    seoDescription: zod.string().nullish(),
    lockVersion: zod.number(),
  }),
});

/**
 * @summary Edit a draft or changes_requested marketing version
 */
export const PatchPlatformMarketingVersionParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const PatchPlatformMarketingVersionBody = zod.object({
  expectedLockVersion: zod.number().min(1),
  title: zod.string().min(1).optional(),
  summary: zod.string().nullish(),
  body: zod.record(zod.string(), zod.unknown()).optional(),
  seoTitle: zod.string().nullish(),
  seoDescription: zod.string().nullish(),
  robots: zod.string().nullish(),
});

export const PatchPlatformMarketingVersionResponse = zod.object({
  version: zod.object({
    id: zod.string().uuid(),
    documentId: zod.string().uuid(),
    locale: zod.string(),
    version: zod.number(),
    status: zod.enum([
      "draft",
      "in_review",
      "changes_requested",
      "approved",
      "scheduled",
      "published",
      "superseded",
      "archived",
    ]),
    title: zod.string(),
    summary: zod.string().nullish(),
    body: zod.record(zod.string(), zod.unknown()),
    seoTitle: zod.string().nullish(),
    seoDescription: zod.string().nullish(),
    lockVersion: zod.number(),
  }),
});

/**
 * @summary Unpublished preview payload for a marketing version
 */
export const PreviewPlatformMarketingVersionParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const PreviewPlatformMarketingVersionResponse = zod.object({
  preview: zod.record(zod.string(), zod.unknown()),
});

/**
 * @summary Compare two marketing versions
 */
export const ComparePlatformMarketingVersionsParams = zod.object({
  leftId: zod.coerce.string().uuid(),
  rightId: zod.coerce.string().uuid(),
});

export const ComparePlatformMarketingVersionsResponse = zod.object({
  left: zod.record(zod.string(), zod.unknown()),
  right: zod.record(zod.string(), zod.unknown()),
  diffs: zod.array(
    zod.object({
      field: zod.string(),
      before: zod.unknown().optional(),
      after: zod.unknown().optional(),
    }),
  ),
});

/**
 * Permission is enforced per transition (propose/review/publish). Dual-control
prevents author self-approve and self-publish. Optimistic concurrency via
expectedLockVersion.

 * @summary Apply a governed marketing lifecycle transition
 */
export const TransitionPlatformMarketingVersionParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const transitionPlatformMarketingVersionBodyReasonMin = 3;

export const TransitionPlatformMarketingVersionBody = zod.object({
  transition: zod.enum([
    "submit_review",
    "request_changes",
    "approve",
    "reject",
    "schedule",
    "publish",
    "unpublish",
    "archive",
    "revise",
  ]),
  expectedLockVersion: zod.number().min(1).optional(),
  scheduledAt: zod.coerce.date().optional(),
  reason: zod
    .string()
    .min(transitionPlatformMarketingVersionBodyReasonMin)
    .optional(),
});

export const TransitionPlatformMarketingVersionResponse = zod.object({
  version: zod.object({
    id: zod.string().uuid(),
    documentId: zod.string().uuid(),
    locale: zod.string(),
    version: zod.number(),
    status: zod.enum([
      "draft",
      "in_review",
      "changes_requested",
      "approved",
      "scheduled",
      "published",
      "superseded",
      "archived",
    ]),
    title: zod.string(),
    summary: zod.string().nullish(),
    body: zod.record(zod.string(), zod.unknown()),
    seoTitle: zod.string().nullish(),
    seoDescription: zod.string().nullish(),
    lockVersion: zod.number(),
  }),
});

/**
 * @summary List recoverable post-publish side-effect failures
 */
export const ListPlatformMarketingPublishFailuresParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const ListPlatformMarketingPublishFailuresResponse = zod.object({
  failures: zod.array(zod.record(zod.string(), zod.unknown())),
});

/**
 * @summary Reconcile failed post-publish side effects
 */
export const ReconcilePlatformMarketingPublishParams = zod.object({
  id: zod.coerce.string().uuid(),
});

export const reconcilePlatformMarketingPublishBodyKindDefault = `all`;

export const ReconcilePlatformMarketingPublishBody = zod.object({
  kind: zod
    .enum(["cache", "notify", "all"])
    .default(reconcilePlatformMarketingPublishBodyKindDefault),
});

export const ReconcilePlatformMarketingPublishResponse = zod.object({
  result: zod.record(zod.string(), zod.unknown()),
});

/**
 * @summary Create a successor draft from a published/archived/superseded version
 */
export const RollbackPlatformMarketingVersionParams = zod.object({
  id: zod.coerce.string().uuid(),
});
