/**
 * OpenAPI operation metadata generated from lib/api-spec/openapi-contact-crm.yaml
 * by scripts/sync-contact-crm-ops.mjs. This is not a request/response contract.
 * Types and fetch operations live in ./contact-generated (Orval).
 */
export const CONTACT_CRM_OPERATIONS = {
  getContactBootstrap: { method: "GET", path: "/contact/bootstrap" },
  submitContactInquiry: { method: "POST", path: "/contact/inquiries" },
  inboundContactEmailWebhook: { method: "POST", path: "/contact/webhooks/inbound-email" },
  microsoftGraphMailWebhook: { method: "POST", path: "/contact/webhooks/microsoft-graph/mail" },
  schedulingContactWebhook: { method: "POST", path: "/contact/webhooks/scheduling" },
  whatsappContactWebhookGet: { method: "GET", path: "/contact/webhooks/whatsapp" },
  whatsappContactWebhook: { method: "POST", path: "/contact/webhooks/whatsapp" },
  metaContactWebhookGet: { method: "GET", path: "/contact/webhooks/meta" },
  metaContactWebhook: { method: "POST", path: "/contact/webhooks/meta" },
  xContactWebhookGet: { method: "GET", path: "/contact/webhooks/x" },
  xContactWebhook: { method: "POST", path: "/contact/webhooks/x" },
  platformAuthLogin: { method: "POST", path: "/platform/auth/login" },
  platformAuthMfaChallenge: { method: "POST", path: "/platform/auth/mfa/challenge" },
  platformAuthLogout: { method: "POST", path: "/platform/auth/logout" },
  platformAuthLogoutAll: { method: "POST", path: "/platform/auth/logout-all" },
  platformAuthSession: { method: "GET", path: "/platform/auth/session" },
  platformAuthForgotPassword: { method: "POST", path: "/platform/auth/forgot-password" },
  platformAuthResetPassword: { method: "POST", path: "/platform/auth/reset-password" },
  platformAuthListSessions: { method: "GET", path: "/platform/auth/sessions" },
  platformAuthRevokeSession: { method: "DELETE", path: "/platform/auth/sessions/{id}" },
  platformAuthVerifyEmail: { method: "POST", path: "/platform/auth/verify-email" },
  platformAuthChangePassword: { method: "POST", path: "/platform/auth/change-password" },
  platformAuthMfaEnroll: { method: "POST", path: "/platform/auth/mfa/enroll" },
  platformAuthMfaConfirm: { method: "POST", path: "/platform/auth/mfa/confirm" },
  platformAuthMfaRecoveryCodes: { method: "POST", path: "/platform/auth/mfa/recovery-codes" },
  platformAuthInviteAccept: { method: "POST", path: "/platform/auth/invite/accept" },
  platformAuthBootstrap: { method: "POST", path: "/platform/auth/bootstrap" },
  getPlatformMe: { method: "GET", path: "/platform/me" },
  listPlatformContactChannels: { method: "GET", path: "/platform/contact/channels" },
  refreshPlatformContactChannelsHealth: { method: "POST", path: "/platform/contact/channels/health-check" },
  listPlatformContactIdentities: { method: "GET", path: "/platform/contact/identities" },
  linkPlatformContactIdentity: { method: "POST", path: "/platform/contact/identities/{id}/link" },
  unlinkPlatformContactIdentity: { method: "POST", path: "/platform/contact/identities/{id}/unlink" },
  retryPlatformContactMessage: { method: "POST", path: "/platform/contact/messages/{id}/retry" },
  listPlatformContactStaff: { method: "GET", path: "/platform/contact/staff" },
  listPlatformContactInquiries: { method: "GET", path: "/platform/contact/inquiries" },
  bulkMarkPlatformInquiriesRead: { method: "POST", path: "/platform/contact/inquiries/bulk-read" },
  getPlatformContactInquiry: { method: "GET", path: "/platform/contact/inquiries/{id}" },
  markPlatformInquiryRead: { method: "POST", path: "/platform/contact/inquiries/{id}/read" },
  replyPlatformInquiry: { method: "POST", path: "/platform/contact/inquiries/{id}/reply" },
  addPlatformInquiryNote: { method: "POST", path: "/platform/contact/inquiries/{id}/notes" },
  forwardPlatformInquiry: { method: "POST", path: "/platform/contact/inquiries/{id}/forward" },
  assignPlatformInquiry: { method: "POST", path: "/platform/contact/inquiries/{id}/assign" },
  setPlatformInquiryStatus: { method: "POST", path: "/platform/contact/inquiries/{id}/status" },
  setPlatformInquiryPriority: { method: "POST", path: "/platform/contact/inquiries/{id}/priority" },
  addPlatformInquiryTag: { method: "POST", path: "/platform/contact/inquiries/{id}/tags" },
  overridePlatformInquiryQualification: { method: "POST", path: "/platform/contact/inquiries/{id}/qualification" },
  generatePlatformInquiryMeeting: { method: "POST", path: "/platform/contact/inquiries/{id}/meeting" },
  convertPlatformInquiryLead: { method: "POST", path: "/platform/contact/inquiries/{id}/convert-lead" },
  runPlatformInquiryMacro: { method: "POST", path: "/platform/contact/inquiries/{id}/macros/{key}" },
  listPlatformContactTemplates: { method: "GET", path: "/platform/contact/templates" },
  createPlatformContactTemplate: { method: "POST", path: "/platform/contact/templates" },
  publishPlatformContactTemplate: { method: "POST", path: "/platform/contact/templates/{id}/publish" },
  createPlatformContactTemplateVersion: { method: "POST", path: "/platform/contact/templates/{id}/versions" },
  getPlatformContactConfig: { method: "GET", path: "/platform/contact/config" },
  updatePlatformTaxonomyItem: { method: "PUT", path: "/platform/contact/taxonomy/{id}" },
  updatePlatformQualificationModel: { method: "PUT", path: "/platform/contact/qualification-models/{id}" },
  updatePlatformWorkflow: { method: "PUT", path: "/platform/contact/workflows/{id}" },
  updatePlatformRoutingRule: { method: "PUT", path: "/platform/contact/routing/{id}" },
  updatePlatformSlaPolicy: { method: "PUT", path: "/platform/contact/sla/{id}" },
  updatePlatformMeetingType: { method: "PUT", path: "/platform/contact/meetings/{id}" },
  updatePlatformMacro: { method: "PUT", path: "/platform/contact/macros/{id}" },
  updatePlatformTag: { method: "PUT", path: "/platform/contact/tags/{id}" },
  updatePlatformNotificationPolicy: { method: "PUT", path: "/platform/contact/notification-policy" },
  updatePlatformBusinessCalendar: { method: "PUT", path: "/platform/contact/business-calendar" },
  updatePlatformRetentionPolicy: { method: "PUT", path: "/platform/contact/retention-policy" },
  updatePlatformSpamBotPolicy: { method: "PUT", path: "/platform/contact/spam-bot-policy" },
  pausePlatformInquirySla: { method: "POST", path: "/platform/contact/inquiries/{id}/sla/pause" },
  resumePlatformInquirySla: { method: "POST", path: "/platform/contact/inquiries/{id}/sla/resume" },
  mergePlatformContacts: { method: "POST", path: "/platform/contact/contacts/merge" },
  listPlatformContactDuplicates: { method: "GET", path: "/platform/contact/contacts/duplicates" },
  listPlatformContactJobs: { method: "GET", path: "/platform/contact/jobs" },
  listPlatformDeadLetterJobs: { method: "GET", path: "/platform/contact/jobs/dead" },
  replayPlatformDeadLetterJob: { method: "POST", path: "/platform/contact/jobs/{id}/replay" },
  listPlatformJobEffects: { method: "GET", path: "/platform/contact/effects" },
  getPlatformJobEffect: { method: "GET", path: "/platform/contact/effects/{key}" },
  reconcilePlatformJobEffect: { method: "POST", path: "/platform/contact/effects/{key}/reconcile" },
  replayPlatformJobEffect: { method: "POST", path: "/platform/contact/effects/{key}/replay" },
  listPlatformWebhookReceipts: { method: "GET", path: "/platform/contact/webhooks" },
  listPlatformDsarRequests: { method: "GET", path: "/platform/contact/dsar" },
  createPlatformDsarRequest: { method: "POST", path: "/platform/contact/dsar" },
  transitionPlatformDsarRequest: { method: "POST", path: "/platform/contact/dsar/{id}/transition" },
  exportPlatformDsarRequest: { method: "POST", path: "/platform/contact/dsar/{id}/export" },
  correctPlatformDsarRequest: { method: "POST", path: "/platform/contact/dsar/{id}/correct" },
  deletePlatformDsarRequest: { method: "POST", path: "/platform/contact/dsar/{id}/delete" },
  objectPlatformDsarRequest: { method: "POST", path: "/platform/contact/dsar/{id}/object" },
  listPlatformAttachments: { method: "GET", path: "/platform/contact/attachments" },
  createPlatformAttachment: { method: "POST", path: "/platform/contact/attachments" },
  releasePlatformAttachmentQuarantine: { method: "POST", path: "/platform/contact/attachments/{id}/release-quarantine" },
  convertPlatformInquiryOpportunity: { method: "POST", path: "/platform/contact/inquiries/{id}/convert-opportunity" },
  getLivez: { method: "GET", path: "/livez" },
  getReadyz: { method: "GET", path: "/readyz" },
  listPlatformContactNotifications: { method: "GET", path: "/platform/contact/notifications" },
  listPlatformSavedViews: { method: "GET", path: "/platform/contact/saved-views" },
  createPlatformSavedView: { method: "POST", path: "/platform/contact/saved-views" },
  getPlatformSavedView: { method: "GET", path: "/platform/contact/saved-views/{id}" },
  updatePlatformSavedView: { method: "PUT", path: "/platform/contact/saved-views/{id}" },
  deletePlatformSavedView: { method: "DELETE", path: "/platform/contact/saved-views/{id}" },
  getPlatformContactAnalytics: { method: "GET", path: "/platform/contact/analytics" },
  bulkAssignPlatformInquiries: { method: "POST", path: "/platform/contact/inquiries/bulk-assign" },
  bulkStatusPlatformInquiries: { method: "POST", path: "/platform/contact/inquiries/bulk-status" },
  listPlatformConfigChanges: { method: "GET", path: "/platform/contact/config/changes" },
  createPlatformConfigChange: { method: "POST", path: "/platform/contact/config/changes" },
  actPlatformConfigChange: { method: "POST", path: "/platform/contact/config/changes/{id}/{action}" },
  replayPlatformWebhookReceipt: { method: "POST", path: "/platform/contact/webhooks/{eventId}/replay" },
  postPlatformGovernanceDsarExport: { method: "POST", path: "/platform/contact/governance/dsar-export" },
  postPlatformLegalHold: { method: "POST", path: "/platform/contact/governance/legal-hold" },
  releasePlatformLegalHold: { method: "POST", path: "/platform/contact/governance/legal-hold/{id}/release" },
  runPlatformRetention: { method: "POST", path: "/platform/contact/governance/retention-run" },
  postPlatformGovernanceAnonymize: { method: "POST", path: "/platform/contact/governance/anonymize" },
  postPlatformGovernanceCorrection: { method: "POST", path: "/platform/contact/governance/correction" },
  invitePlatformStaff: { method: "POST", path: "/platform/contact/staff/invite" },
  listPlatformContactAudit: { method: "GET", path: "/platform/contact/audit" },
  exportPlatformContactDsar: { method: "POST", path: "/platform/contact/contacts/{id}/dsar-export" },
  getPlatformContactDsarExport: { method: "GET", path: "/platform/contact/dsar-exports/{exportId}" },
  getPlatformContactPresence: { method: "GET", path: "/platform/contact/presence" },
  heartbeatPlatformContactPresence: { method: "POST", path: "/platform/contact/presence/heartbeat" },
  acquirePlatformRecordLock: { method: "POST", path: "/platform/contact/locks/acquire" },
  heartbeatPlatformRecordLock: { method: "POST", path: "/platform/contact/locks/{id}/heartbeat" },
  releasePlatformRecordLock: { method: "POST", path: "/platform/contact/locks/{id}/release" },
  overridePlatformRecordLock: { method: "POST", path: "/platform/contact/locks/{id}/override" },
  createPlatformContactExport: { method: "POST", path: "/platform/contact/exports" },
  listPlatformContactExports: { method: "GET", path: "/platform/contact/exports" },
  getPlatformContactExport: { method: "GET", path: "/platform/contact/exports/{id}" },
  cancelPlatformContactExport: { method: "POST", path: "/platform/contact/exports/{id}/cancel" },
  downloadPlatformContactExport: { method: "GET", path: "/platform/contact/exports/{id}/download" },
  listPlatformMarketingDocuments: { method: "GET", path: "/platform/marketing/documents" },
  createPlatformMarketingDocumentDraft: { method: "POST", path: "/platform/marketing/documents" },
  listPlatformMarketingDocumentVersions: { method: "GET", path: "/platform/marketing/documents/{slug}/versions" },
  listPlatformMarketingDocumentAudit: { method: "GET", path: "/platform/marketing/documents/{slug}/audit" },
  getPlatformMarketingVersion: { method: "GET", path: "/platform/marketing/versions/{id}" },
  patchPlatformMarketingVersion: { method: "PATCH", path: "/platform/marketing/versions/{id}" },
  previewPlatformMarketingVersion: { method: "GET", path: "/platform/marketing/versions/{id}/preview" },
  comparePlatformMarketingVersions: { method: "GET", path: "/platform/marketing/versions/{leftId}/compare/{rightId}" },
  transitionPlatformMarketingVersion: { method: "POST", path: "/platform/marketing/versions/{id}/transition" },
  listPlatformMarketingPublishFailures: { method: "GET", path: "/platform/marketing/versions/{id}/publish-failures" },
  reconcilePlatformMarketingPublish: { method: "POST", path: "/platform/marketing/versions/{id}/reconcile-publish" },
  rollbackPlatformMarketingVersion: { method: "POST", path: "/platform/marketing/versions/{id}/rollback" },
} as const;

export type ContactCrmOperationId = keyof typeof CONTACT_CRM_OPERATIONS;

export function contactCrmPath(
  id: ContactCrmOperationId,
  params?: Record<string, string>,
): string {
  let path: string = CONTACT_CRM_OPERATIONS[id].path;
  for (const [key, value] of Object.entries(params ?? {})) {
    path = path.replace(`{${key}}`, encodeURIComponent(value));
  }
  return path;
}
